"""
KruschLaw Legal Document Export Module.
Generates publication-quality, court/client-ready .docx legal briefs with
formal legal headers, UPL disclaimers, assertion-level verification tables,
and cited statutory appendices.
"""

import io
from typing import List, Dict, Optional, Any
from datetime import datetime

import docx
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml import parse_xml, OxmlElement
from docx.oxml.ns import nsdecls, qn


def set_cell_background(cell, hex_color: str):
    """Set background color of a table cell."""
    tcPr = cell._tc.get_or_add_tcPr()
    shd = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{hex_color}"/>')
    tcPr.append(shd)


def set_cell_margins(cell, top=100, bottom=100, left=150, right=150):
    """Set inner padding for table cells."""
    tcPr = cell._tc.get_or_add_tcPr()
    tcMar = OxmlElement('w:tcMar')
    for m, val in [('top', top), ('bottom', bottom), ('left', left), ('right', right)]:
        node = OxmlElement(f'w:{m}')
        node.set(qn('w:w'), str(val))
        node.set(qn('w:type'), 'dxa')
        tcMar.append(node)
    tcPr.append(tcMar)


def generate_brief_docx(
    brief_content: str,
    matter_title: str,
    matter_number: Optional[str] = None,
    client_name: Optional[str] = None,
    claims_audit: Optional[List[Dict[str, Any]]] = None,
    retrieved_laws: Optional[List[Dict[str, Any]]] = None,
    disclaimer: Optional[str] = None
) -> bytes:
    """
    Format a generated legal brief into a professional, styled Microsoft Word (.docx) document.
    """
    doc = docx.Document()

    # 1. Page Setup - 1-inch margins
    for section in doc.sections:
        section.top_margin = Inches(1.0)
        section.bottom_margin = Inches(1.0)
        section.left_margin = Inches(1.0)
        section.right_margin = Inches(1.0)
        section.header.is_linked_to_previous = False
        section.footer.is_linked_to_previous = False

        # Header
        header_p = section.header.paragraphs[0]
        header_p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
        h_run = header_p.add_run(f"CONFIDENTIAL ATTORNEY-CLIENT WORK PRODUCT | {matter_number or 'PRELIMINARY'}")
        h_run.font.name = "Arial"
        h_run.font.size = Pt(8.5)
        h_run.font.color.rgb = RGBColor(120, 120, 120)

        # Footer
        footer_p = section.footer.paragraphs[0]
        footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        f_run = footer_p.add_run("Generated by KruschLaw Sovereign Legal Engine — Subject to Independent Attorney Verification")
        f_run.font.name = "Arial"
        f_run.font.size = Pt(8.0)
        f_run.font.color.rgb = RGBColor(140, 140, 140)

    # 2. Document Title / Caption
    title_p = doc.add_paragraph()
    title_p.paragraph_format.space_before = Pt(0)
    title_p.paragraph_format.space_after = Pt(4)
    t_run = title_p.add_run("LEGAL MEMORANDUM & STATUTORY ANALYSIS")
    t_run.font.name = "Times New Roman"
    t_run.font.size = Pt(18)
    t_run.font.bold = True
    t_run.font.color.rgb = RGBColor(20, 35, 60)

    # Caption Table
    caption_table = doc.add_table(rows=4, cols=2)
    caption_table.alignment = WD_TABLE_ALIGNMENT.CENTER
    caption_table.autofit = False

    caption_data = [
        ("MATTER:", matter_title),
        ("MATTER NUMBER:", matter_number or "N/A"),
        ("CLIENT:", client_name or "Confidential"),
        ("DATE PREPARED:", datetime.now().strftime("%B %d, %Y"))
    ]

    for idx, (label, val) in enumerate(caption_data):
        row = caption_table.rows[idx]
        cell_lbl, cell_val = row.cells[0], row.cells[1]
        cell_lbl.width = Inches(1.8)
        cell_val.width = Inches(4.7)

        p_lbl = cell_lbl.paragraphs[0]
        p_lbl.paragraph_format.space_after = Pt(2)
        r_l = p_lbl.add_run(label)
        r_l.font.name = "Arial"
        r_l.font.size = Pt(9.5)
        r_l.font.bold = True
        r_l.font.color.rgb = RGBColor(70, 70, 70)

        p_val = cell_val.paragraphs[0]
        p_val.paragraph_format.space_after = Pt(2)
        r_v = p_val.add_run(val)
        r_v.font.name = "Arial"
        r_v.font.size = Pt(9.5)

    doc.add_paragraph().paragraph_format.space_after = Pt(6)

    # 3. Ethics & UPL Disclaimer Box
    if disclaimer:
        disc_table = doc.add_table(rows=1, cols=1)
        disc_cell = disc_table.rows[0].cells[0]
        disc_cell.width = Inches(6.5)
        set_cell_background(disc_cell, "F8F9FA")
        set_cell_margins(disc_cell, top=140, bottom=140, left=180, right=180)

        dp = disc_cell.paragraphs[0]
        dp.paragraph_format.space_after = Pt(0)
        d_lbl = dp.add_run("⚖️ MANDATORY ETHICAL & REGULATORY NOTICE: ")
        d_lbl.font.name = "Arial"
        d_lbl.font.size = Pt(8.5)
        d_lbl.font.bold = True
        d_lbl.font.color.rgb = RGBColor(160, 40, 20)

        d_body = dp.add_run(disclaimer)
        d_body.font.name = "Arial"
        d_body.font.size = Pt(8.5)
        d_body.font.italic = True
        d_body.font.color.rgb = RGBColor(80, 80, 80)

        doc.add_paragraph().paragraph_format.space_after = Pt(8)

    # 4. Primary Legal Brief Content
    for line in brief_content.splitlines():
        line_s = line.strip()
        if not line_s:
            continue

        if line_s.startswith("### "):
            hp = doc.add_paragraph()
            hp.paragraph_format.space_before = Pt(14)
            hp.paragraph_format.space_after = Pt(4)
            hp.paragraph_format.keep_with_next = True
            hrun = hp.add_run(line_s.replace("### ", "").upper())
            hrun.font.name = "Times New Roman"
            hrun.font.size = Pt(13)
            hrun.font.bold = True
            hrun.font.color.rgb = RGBColor(30, 45, 80)
        elif line_s.startswith("## "):
            hp = doc.add_paragraph()
            hp.paragraph_format.space_before = Pt(16)
            hp.paragraph_format.space_after = Pt(6)
            hp.paragraph_format.keep_with_next = True
            hrun = hp.add_run(line_s.replace("## ", "").upper())
            hrun.font.name = "Times New Roman"
            hrun.font.size = Pt(14)
            hrun.font.bold = True
            hrun.font.color.rgb = RGBColor(15, 30, 65)
        elif line_s.startswith("> "):
            qp = doc.add_paragraph()
            qp.paragraph_format.left_indent = Inches(0.4)
            qp.paragraph_format.right_indent = Inches(0.4)
            qp.paragraph_format.space_after = Pt(4)
            qrun = qp.add_run(line_s.replace("> ", ""))
            qrun.font.name = "Times New Roman"
            qrun.font.size = Pt(10.5)
            qrun.font.italic = True
        elif any(marker in line_s for marker in ("[CLAIM REFUSED:", "[COVERAGE GAP:", "[UNAUTHORIZED CITATION STRIPPED:")):
            gap_table = doc.add_table(rows=1, cols=1)
            gap_table.alignment = WD_TABLE_ALIGNMENT.CENTER
            gap_cell = gap_table.rows[0].cells[0]
            gap_cell.width = Inches(6.5)
            set_cell_background(gap_cell, "FFF3E0")
            set_cell_margins(gap_cell, top=100, bottom=100, left=140, right=140)
            gp = gap_cell.paragraphs[0]
            gp.paragraph_format.space_after = Pt(0)
            gr_lbl = gp.add_run("⚠️ STATUTORY COVERAGE GAP (UNGROUNDED / REFUSED PROPOSITION):\n")
            gr_lbl.font.name = "Arial"
            gr_lbl.font.size = Pt(9.5)
            gr_lbl.font.bold = True
            gr_lbl.font.color.rgb = RGBColor(180, 50, 20)
            gr_text = gp.add_run(line_s)
            gr_text.font.name = "Arial"
            gr_text.font.size = Pt(9.0)
            gr_text.font.italic = True
            gr_text.font.color.rgb = RGBColor(90, 70, 50)
            doc.add_paragraph().paragraph_format.space_after = Pt(4)
        elif line_s.startswith(("- ", "* ")):
            bp = doc.add_paragraph(style='List Bullet')
            bp.paragraph_format.space_after = Pt(3)
            brun = bp.add_run(line_s[2:])
            brun.font.name = "Times New Roman"
            brun.font.size = Pt(11)
        elif line_s.startswith(("---", "===")):
            continue
        else:
            bp = doc.add_paragraph()
            bp.paragraph_format.space_after = Pt(6)
            bp.paragraph_format.line_spacing = 1.15
            brun = bp.add_run(line_s)
            brun.font.name = "Times New Roman"
            brun.font.size = Pt(11)

    # 5. Assertion Grounding Scorecard Table (if provided)
    if claims_audit:
        doc.add_page_break()
        sec_h = doc.add_paragraph()
        sec_h.paragraph_format.space_before = Pt(12)
        sec_h.paragraph_format.space_after = Pt(6)
        s_run = sec_h.add_run("APPENDIX A: ASSERTION-LEVEL GROUNDING AUDIT REPORT")
        s_run.font.name = "Times New Roman"
        s_run.font.size = Pt(14)
        s_run.font.bold = True
        s_run.font.color.rgb = RGBColor(20, 35, 60)

        intro = doc.add_paragraph()
        intro.paragraph_format.space_after = Pt(6)
        irun = intro.add_run(
            "Every discrete proposition in this brief was automatically cross-referenced against the air-gapped "
            "statutory corpus to verify factual overlap and detect hallucinations or stale authority."
        )
        irun.font.name = "Arial"
        irun.font.size = Pt(9.5)
        irun.font.italic = True

        audit_table = doc.add_table(rows=1, cols=4)
        audit_table.alignment = WD_TABLE_ALIGNMENT.CENTER
        headers = ["Claim Proposition", "Status", "Cited Authority", "Source Excerpt / Verification Rationale"]
        col_widths = [Inches(2.2), Inches(1.1), Inches(1.1), Inches(2.1)]

        hdr_cells = audit_table.rows[0].cells
        for idx, (title, w) in enumerate(zip(headers, col_widths)):
            hdr_cells[idx].width = w
            set_cell_background(hdr_cells[idx], "203045")
            set_cell_margins(hdr_cells[idx], top=80, bottom=80, left=100, right=100)
            p = hdr_cells[idx].paragraphs[0]
            p.paragraph_format.space_after = Pt(0)
            r = p.add_run(title)
            r.font.name = "Arial"
            r.font.size = Pt(9)
            r.font.bold = True
            r.font.color.rgb = RGBColor(255, 255, 255)

        status_colors = {
            "supported": "E8F5E9",
            "invented_citation": "FFEBEE",
            "wrong_proposition": "FFF3E0",
            "abstain": "FFF8E1",
            "stale_law": "EDE7F6"
        }

        for claim in claims_audit:
            row_cells = audit_table.add_row().cells
            st = claim.get("status", "unknown")
            bg = status_colors.get(st, "FFFFFF")

            # Col 0: Claim
            row_cells[0].width = col_widths[0]
            p0 = row_cells[0].paragraphs[0]
            p0.paragraph_format.space_after = Pt(0)
            r0 = p0.add_run(claim.get("claim", ""))
            r0.font.name = "Arial"
            r0.font.size = Pt(8.5)

            # Col 1: Status
            row_cells[1].width = col_widths[1]
            set_cell_background(row_cells[1], bg)
            p1 = row_cells[1].paragraphs[0]
            p1.paragraph_format.space_after = Pt(0)
            r1 = p1.add_run(st.replace("_", " ").upper())
            r1.font.name = "Arial"
            r1.font.size = Pt(8.0)
            r1.font.bold = True

            # Col 2: Citation
            row_cells[2].width = col_widths[2]
            p2 = row_cells[2].paragraphs[0]
            p2.paragraph_format.space_after = Pt(0)
            r2 = p2.add_run(claim.get("citation", "General"))
            r2.font.name = "Arial"
            r2.font.size = Pt(8.5)

            # Col 3: Excerpt / Rationale
            row_cells[3].width = col_widths[3]
            p3 = row_cells[3].paragraphs[0]
            p3.paragraph_format.space_after = Pt(0)
            r3 = p3.add_run(f'"{claim.get("source_excerpt", "")}"\n({claim.get("reason", "")})')
            r3.font.name = "Arial"
            r3.font.size = Pt(8.0)
            r3.font.italic = True

            for c in row_cells:
                set_cell_margins(c, top=60, bottom=60, left=80, right=80)

    # 6. Authorities Cited Appendix
    if retrieved_laws:
        doc.add_page_break()
        auth_h = doc.add_paragraph()
        auth_h.paragraph_format.space_before = Pt(12)
        auth_h.paragraph_format.space_after = Pt(6)
        arun = auth_h.add_run("APPENDIX B: TABLE OF AUTHORITIES RETRIEVED")
        arun.font.name = "Times New Roman"
        arun.font.size = Pt(14)
        arun.font.bold = True
        arun.font.color.rgb = RGBColor(20, 35, 60)

        auth_table = doc.add_table(rows=1, cols=4)
        auth_table.alignment = WD_TABLE_ALIGNMENT.CENTER
        headers_b = ["Section", "Statutory Title", "Authority Class", "Effective Date"]
        col_widths_b = [Inches(1.5), Inches(2.7), Inches(1.3), Inches(1.0)]

        hdr_cells_b = auth_table.rows[0].cells
        for idx, (title, w) in enumerate(zip(headers_b, col_widths_b)):
            hdr_cells_b[idx].width = w
            set_cell_background(hdr_cells_b[idx], "304055")
            set_cell_margins(hdr_cells_b[idx], top=80, bottom=80, left=100, right=100)
            p = hdr_cells_b[idx].paragraphs[0]
            p.paragraph_format.space_after = Pt(0)
            r = p.add_run(title)
            r.font.name = "Arial"
            r.font.size = Pt(9)
            r.font.bold = True
            r.font.color.rgb = RGBColor(255, 255, 255)

        for law in retrieved_laws:
            r_cells = auth_table.add_row().cells
            r_cells[0].width = col_widths_b[0]
            p0 = r_cells[0].paragraphs[0]
            r0 = p0.add_run(law.get("section", "N/A"))
            r0.font.name = "Arial"
            r0.font.size = Pt(8.5)
            r0.font.bold = True

            r_cells[1].width = col_widths_b[1]
            p1 = r_cells[1].paragraphs[0]
            r1 = p1.add_run(f"{law.get('title', 'N/A')}\n({law.get('jurisdiction', '')})")
            r1.font.name = "Arial"
            r1.font.size = Pt(8.5)

            r_cells[2].width = col_widths_b[2]
            p2 = r_cells[2].paragraphs[0]
            r2 = p2.add_run((law.get("authority_class") or "ordinance").replace("_", " ").title())
            r2.font.name = "Arial"
            r2.font.size = Pt(8.0)

            r_cells[3].width = col_widths_b[3]
            p3 = r_cells[3].paragraphs[0]
            eff = law.get("effective_date") or "Active"
            r3 = p3.add_run(str(eff)[:10] if eff else "N/A")
            r3.font.name = "Arial"
            r3.font.size = Pt(8.0)

            for c in r_cells:
                set_cell_margins(c, top=60, bottom=60, left=80, right=80)

    # Save to buffer
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()
