import re
import json
import math
import uuid
import logging
import hashlib
import threading
import difflib
from datetime import datetime, timezone
from collections import OrderedDict
import httpx
from typing import List, Dict, Optional, Tuple, Set, Any
from sqlalchemy import text
from sqlalchemy.orm import Session

from .config import settings
from .db import SessionLocal, LawVector, GroundingReport, MatterEvidence

logger = logging.getLogger("kruschlaw.rag")

UPL_DISCLAIMER = (
    "DISCLAIMER: This analysis was generated by KruschLaw, an offline, air-gapped AI research engine. "
    "This material is provided strictly for exploratory legal research and preliminary issue-spotting. "
    "It does NOT constitute legal advice, formal representation, or an attorney-client relationship. "
    "A licensed attorney admitted to practice in the relevant jurisdiction must independently verify "
    "all cited statutes, local ordinances, and analytical conclusions prior to taking any formal legal action."
)

# DEPRECATED: Arbitrary authority weight multipliers (1.25/1.15/1.0/0.8) are replaced by the
# deterministic Jurisdiction Machine (`filter_authorities_by_jurisdiction`). Maintained for backward compatibility.
AUTHORITY_WEIGHTS = {
    "controlling_statute": 1.0,
    "implementing_regulation": 1.0,
    "municipal_ordinance": 1.0,
    "secondary_commentary": 1.0,
}

LEGAL_ISSUE_RULES: List[Dict[str, Any]] = [
    {
        "issue": "Notice of Rent Adjustment Program (RAP) Compliance",
        "jurisdiction": "Oakland / California",
        "governing_authorities": "OMC § 8.22.030, Cal. Civ. Code § 1947.12",
        "keywords": [
            r"\brent\s+increase\b", r"\brent\s+hike\b", r"\braised\s+rent\b", r"\bincreased\s+(?:the\s+)?rent\b",
            r"\brap\s+notice\b", r"\brent\s+adjustment\b", r"\bnotice\s+of\s+rent\b"
        ],
        "statutory_terms": "OMC 8.22.030 Notice of Rent Adjustment Program RAP Notice Cal Civ Code 1947.12 allowable rent increase petition rights"
    },
    {
        "issue": "Security Deposit Retention & Itemization",
        "jurisdiction": "California Civil Code",
        "governing_authorities": "Cal. Civ. Code § 1950.5",
        "keywords": [
            r"\bsecurity\s+deposit\b", r"\bdeposit\s+return\b", r"\brefund\s+deposit\b",
            r"\bcleaning\s+fee\b", r"\bdeductions?\b", r"\bitemized\s+statement\b",
            r"\bkept\s+(?:the\s+|my\s+)?deposit\b", r"\bwithheld\s+(?:the\s+|my\s+)?deposit\b"
        ],
        "statutory_terms": "Cal Civ Code 1950.5 itemized disposition of security deposit 21 calendar days bad faith retention statutory damages normal wear and tear"
    },
    {
        "issue": "Breach of Implied Warranty of Habitability",
        "jurisdiction": "California Civil Code / Health & Safety",
        "governing_authorities": "Cal. Civ. Code § 1941.1, Cal. Health & Safety Code § 17920.3",
        "keywords": [
            r"\bmold\b", r"\bno\s+heat\b", r"\bbroken\s+heater\b", r"\bhot\s+water\b",
            r"\broaches?\b", r"\brats?\b", r"\bmice\b", r"\bvermin\b", r"\binfestation\b",
            r"\bleaking\s+roof\b", r"\bplumbing\s+leak\b", r"\buntenantable\b", r"\bhabitability\b"
        ],
        "statutory_terms": "Cal Civ Code 1941.1 implied warranty of habitability tenantable dwelling effective waterproofing weather protection heating plumbing repair and deduct"
    },
    {
        "issue": "Unlawful Self-Help Eviction & Utility Interruption",
        "jurisdiction": "California Civil Code",
        "governing_authorities": "Cal. Civ. Code § 789.3",
        "keywords": [
            r"\blocked?\s+out\b", r"\blockout\b", r"\bchanged\s+(?:the\s+)?locks?\b", r"\bdeadbolt\b",
            r"\bpadlock\b", r"\bshut\s+off\s+(?:water|power|electricity|gas)\b", r"\bcut\s+(?:the\s+)?power\b",
            r"\bremoved\s+(?:door|windows?)\b", r"\bthrew\s+out\s+belongings\b"
        ],
        "statutory_terms": "Cal Civ Code 789.3 unlawful self-help eviction interruption of utility service statutory damages 100 dollars per day forcible entry without court process"
    },
    {
        "issue": "Just Cause Eviction & Owner Move-In (OMI) Defense",
        "jurisdiction": "Oakland / California",
        "governing_authorities": "OMC § 8.22.360, Cal. Civ. Code § 1946.2",
        "keywords": [
            r"\bjust\s+cause\b", r"\bowner\s+move\s*in\b", r"\brelative\s+move\s*in\b",
            r"\bnephew\s+move\s*in\b", r"\bellis\s+act\b", r"\bno\s+fault\s+eviction\b",
            r"\bterminate\s+tenancy\b", r"\bnotice\s+to\s+vacate\b"
        ],
        "statutory_terms": "OMC 8.22.360 just cause for eviction good faith owner occupancy principal residence enumerated grounds 1946.2"
    },
    {
        "issue": "Tenant Relocation Assistance & Displacement Protections",
        "jurisdiction": "Los Angeles / Oakland",
        "governing_authorities": "LAMC § 151.09, OMC § 8.22.360",
        "keywords": [
            r"\brelocation\s+fees?\b", r"\brelocation\s+assistance\b", r"\bdisplaced\s+tenants?\b",
            r"\belderly\s+tenant\b", r"\bdisabled\s+tenant\b", r"\brso\s+building\b"
        ],
        "statutory_terms": "LAMC 151.09 relocation fees displaced tenants rent stabilization ordinance RSO graduated payment protected status"
    },
    {
        "issue": "Retaliatory Eviction Defense",
        "jurisdiction": "California Civil Code",
        "governing_authorities": "Cal. Civ. Code § 1942.5",
        "keywords": [
            r"\bretaliat(?:ion|ed|ory)\b", r"\bcomplained\s+about\b", r"\bcode\s+enforcement\b",
            r"\breported\s+(?:violation|landlord)\b", r"\bexercis(?:ed|ing)\s+rights\b"
        ],
        "statutory_terms": "Cal Civ Code 1942.5 retaliatory eviction 180 days exercise of tenant rights reporting habitability violation"
    },
    {
        "issue": "Residential Noise Nuisance Limits",
        "jurisdiction": "San Francisco Police Code",
        "governing_authorities": "SF Police Code § 2909",
        "keywords": [
            r"\bamplified\s+sound\b", r"\bdecibels?\b", r"\bdba\b", r"\bnighttime\s+noise\b",
            r"\bloud\s+music\b", r"\bambient\s+noise\b"
        ],
        "statutory_terms": "SF Police Code Section 2909 ambient noise residential zone dBA 5 dBA above ambient 10:00 PM to 7:00 AM"
    },
    {
        "issue": "Short-Term Residential Rental Restrictions",
        "jurisdiction": "San Francisco Administrative Code",
        "governing_authorities": "SF Admin. Code Chapter 41A § 41A.5",
        "keywords": [
            r"\bairbnb\b", r"\bshort\s+term\s+rental\b", r"\bvrbo\b", r"\bvacation\s+rental\b",
            r"\bprimary\s+resident\b", r"\b275\s+days\b"
        ],
        "statutory_terms": "SF Administrative Code Chapter 41A Section 41A.5 primary permanent resident reside at least 275 days calendar year"
    }
]


def expand_legal_query(text_content: str) -> Tuple[str, List[Dict[str, str]]]:
    """
    Spot legal issues from colloquial tenant/landlord fact patterns and synthesize
    canonical statutory search terms.
    Returns (expanded_query_string, spotted_issues_list).
    """
    if not text_content or not text_content.strip():
        return text_content, []

    spotted: List[Dict[str, str]] = []
    collected_terms: List[str] = []
    text_lower = text_content.lower()

    for rule in LEGAL_ISSUE_RULES:
        matched = False
        for kw in rule["keywords"]:
            if re.search(kw, text_lower):
                matched = True
                break
        if matched:
            spotted.append({
                "issue": rule["issue"],
                "jurisdiction": rule["jurisdiction"],
                "governing_authorities": rule["governing_authorities"]
            })
            collected_terms.append(rule["statutory_terms"])

    if collected_terms:
        expanded_query = f"{text_content} {' '.join(collected_terms)}"
    else:
        expanded_query = text_content

    return expanded_query, spotted


class RetrievalError(RuntimeError):
    """Raised when statutory or ordinance search against the database fails."""
    pass


class EmbeddingCache:
    """Thread-safe LRU cache for embeddings keyed by model and sha256 text hash."""
    def __init__(self, maxsize: int = 10000):
        self.maxsize = maxsize
        self._cache: OrderedDict[str, List[float]] = OrderedDict()
        self._lock = threading.Lock()
        self.hits = 0
        self.misses = 0

    def _key(self, model: str, text: str) -> str:
        text_hash = hashlib.sha256(text.encode("utf-8")).hexdigest()
        return f"{model}:{text_hash}"

    def get(self, model: str, text: str) -> Optional[List[float]]:
        key = self._key(model, text)
        with self._lock:
            if key in self._cache:
                self.hits += 1
                self._cache.move_to_end(key)
                return self._cache[key]
            self.misses += 1
            return None

    def set(self, model: str, text: str, vector: List[float]) -> None:
        key = self._key(model, text)
        with self._lock:
            self._cache[key] = vector
            self._cache.move_to_end(key)
            if len(self._cache) > self.maxsize:
                self._cache.popitem(last=False)

    def stats(self) -> Dict[str, Any]:
        with self._lock:
            total = self.hits + self.misses
            hit_ratio = (self.hits / total) if total > 0 else 0.0
            return {
                "size": len(self._cache),
                "maxsize": self.maxsize,
                "hits": self.hits,
                "misses": self.misses,
                "hit_ratio": round(hit_ratio, 4)
            }

    def clear(self) -> None:
        with self._lock:
            self._cache.clear()
            self.hits = 0
            self.misses = 0


embedding_cache = EmbeddingCache(maxsize=10000)


def get_embeddings_batch(queries: List[str]) -> List[List[float]]:
    """Generate vector embeddings in batch via Ollama API with LRU cache."""
    if not queries:
        return []
    clean_queries = [q.strip() if q and q.strip() else " " for q in queries]

    results: List[Optional[List[float]]] = [None] * len(clean_queries)
    miss_indices: List[int] = []
    miss_texts: List[str] = []

    for idx, q in enumerate(clean_queries):
        cached = embedding_cache.get(settings.OLLAMA_EMBED_MODEL, q)
        if cached is not None:
            results[idx] = cached
        else:
            miss_indices.append(idx)
            miss_texts.append(q)

    if not miss_texts:
        return [r for r in results if r is not None]

    payload = {
        "model": settings.OLLAMA_EMBED_MODEL,
        "input": miss_texts
    }
    fetched: List[List[float]] = []
    try:
        timeout = max(settings.EMBED_TIMEOUT, settings.EMBED_TIMEOUT * (len(miss_texts) / 8.0))
        with httpx.Client(timeout=timeout) as client:
            resp = client.post(f"{settings.OLLAMA_EMBED_HOST}/api/embed", json=payload)
            if resp.status_code == 200:
                data = resp.json()
                embeddings = data.get("embeddings", [])
                if len(embeddings) == len(miss_texts):
                    fetched = embeddings
            if not fetched:
                fetched = [get_embedding(q) for q in miss_texts]
    except Exception as e:
        logger.warning(f"Batch embedding request failed ({e}), falling back to sequential embedding.")
        fetched = [get_embedding(q) for q in miss_texts]

    for idx, text_val, vec in zip(miss_indices, miss_texts, fetched):
        embedding_cache.set(settings.OLLAMA_EMBED_MODEL, text_val, vec)
        results[idx] = vec

    return [r for r in results if r is not None]


def get_embedding(query: str) -> List[float]:
    """Generate a vector embedding via Ollama API with LRU cache."""
    if not query or not query.strip():
        raise ValueError("Cannot embed empty text.")

    cached = embedding_cache.get(settings.OLLAMA_EMBED_MODEL, query)
    if cached is not None:
        return cached

    payload = {
        "model": settings.OLLAMA_EMBED_MODEL,
        "input": query
    }

    try:
        with httpx.Client(timeout=settings.EMBED_TIMEOUT) as client:
            resp = client.post(f"{settings.OLLAMA_EMBED_HOST}/api/embed", json=payload)
            if resp.status_code == 404:
                resp = client.post(
                    f"{settings.OLLAMA_EMBED_HOST}/api/embeddings",
                    json={"model": settings.OLLAMA_EMBED_MODEL, "prompt": query}
                )
                resp.raise_for_status()
                embedding = resp.json().get("embedding", [])
                if embedding:
                    embedding_cache.set(settings.OLLAMA_EMBED_MODEL, query, embedding)
                    return embedding
                raise ValueError("Legacy Ollama endpoint returned empty embedding.")

            resp.raise_for_status()
            data = resp.json()
            embeddings = data.get("embeddings", [])
            if embeddings and len(embeddings) > 0 and len(embeddings[0]) > 0:
                result_vec = embeddings[0]
                embedding_cache.set(settings.OLLAMA_EMBED_MODEL, query, result_vec)
                return result_vec
            raise ValueError(f"Ollama returned unexpected payload structure: {data}")

    except httpx.ConnectError as e:
        logger.error(f"Failed to connect to Ollama embedding service at {settings.OLLAMA_EMBED_HOST}: {e}")
        raise ConnectionError(
            f"Could not connect to Ollama at {settings.OLLAMA_EMBED_HOST}. "
            f"Please verify Ollama is running and has the '{settings.OLLAMA_EMBED_MODEL}' model pulled."
        ) from e
    except Exception as e:
        logger.error(f"Embedding generation error: {e}")
        raise


def extract_section_identifiers(text_content: str) -> Set[str]:
    """
    Extract normalized section numbers and statutory identifiers from legal text.
    Handles municipal formats (OMC 8.22.030, LAMC § 151.09, SF Police Code § 2909)
    and California Codes (Cal. Civ. Code § 1950.5(b)).
    """
    if not text_content:
        return set()

    patterns = [
        r'\b(?:OMC|O\.M\.C\.|LAMC|L\.A\.M\.C\.|SFPC|SFAC)\s*(?:§+|Section|Sec\.?)?\s*([0-9]+[A-Za-z0-9\.\-\(\)]*)',
        r'\b(?:Cal\.\s*Civ\.\s*Code|California\s*Civil\s*Code|Civ\.\s*Code|CC)\s*(?:§+|Section|Sec\.?)?\s*([0-9]+[A-Za-z0-9\.\-\(\)]*)',
        r'\b(?:Police\s*Code|Admin\.\s*Code|Health\s*&\s*Saf\.\s*Code|Gov\.\s*Code)\s*(?:§+|Section|Sec\.?)?\s*([0-9]+[A-Za-z0-9\.\-\(\)]*)',
        r'(?:§+|Section|Sec\.)\s*([0-9]+[A-Za-z0-9\.\-\(\)]*)',
    ]

    sections = set()
    for pattern in patterns:
        for m in re.finditer(pattern, text_content, re.IGNORECASE):
            raw_sec = m.group(1).strip().rstrip('.,;:')
            if raw_sec:
                sections.add(raw_sec)
    return sections


def is_section_grounded(cited_sec: str, authorized_sections: Set[str]) -> bool:
    """Check if a cited section matches or derives from an authorized section."""
    cited_norm = re.sub(r'[\(\)\[\]\s]', '', cited_sec).lower()
    for auth in authorized_sections:
        auth_norm = re.sub(r'[\(\)\[\]\s]', '', auth).lower()
        if cited_norm == auth_norm or cited_norm.startswith(auth_norm) or auth_norm.startswith(cited_norm):
            return True
    return False


def verify_citation_grounding(analysis_text: str, laws: List[Dict]) -> Tuple[bool, List[str], str]:
    """
    Verify whether statutory citations and quote spans in the generated brief
    are grounded in retrieved laws.
    """
    if not laws:
        return False, [], ""

    authorized_sections: Set[str] = set()
    corpus_text = ""
    for law in laws:
        authorized_sections.update(extract_section_identifiers(law.get("section", "")))
        authorized_sections.update(extract_section_identifiers(law.get("title", "")))
        corpus_text += " " + (law.get("content") or "")

    corpus_lower = corpus_text.lower()

    raw_citations = extract_section_identifiers(analysis_text)
    valid_citations = {s for s in raw_citations if len(s) > 1 or (s.isdigit() and int(s) > 10)}

    ungrounded_cites = []
    for citation in sorted(valid_citations):
        if not is_section_grounded(citation, authorized_sections):
            ungrounded_cites.append(citation)

    quotes = re.findall(r'["“]([^"”]{20,})["”]', analysis_text)
    ungrounded_quotes = []
    for q in quotes:
        clean_q = re.sub(r'\s+', ' ', q).strip().lower()
        if clean_q not in corpus_lower and len(clean_q) > 25:
            q_words = set(clean_q.split())
            if q_words and sum(1 for w in q_words if w in corpus_lower) / len(q_words) < 0.6:
                ungrounded_quotes.append(q[:60] + ("..." if len(q) > 60 else ""))

    issues = []
    if ungrounded_cites:
        formatted_cites = "\n".join(f"> - `Section {c}`" for c in ungrounded_cites)
        issues.append(f"> **Ungrounded Statutory Sections** (not found in retrieved authorities):\n{formatted_cites}")
    if ungrounded_quotes:
        formatted_quotes = "\n".join(f"> - *\"{q}\"*" for q in ungrounded_quotes)
        issues.append(f"> **Unverified Verbatim Quotes** (quote text not found in retrieved authorities):\n{formatted_quotes}")

    if issues:
        notice = (
            "\n\n---\n\n"
            "> ⚠️ **Citation & Grounding Advisory (Potential Hallucination Risk)**:\n"
            "> The following citations or quotes in this brief were **not verified against retrieved authorities**:\n"
            + "\n>\n".join(issues) +
            "\n>\n"
            "> KruschLaw mandates that counsel independently verify whether these provisions and excerpts are authentic, "
            "controlling, and unrepealed prior to relying upon them."
        )
        return False, ungrounded_cites + ungrounded_quotes, notice
    else:
        notice = (
            "\n\n---\n\n"
            "> 🛡️ **Citation Grounding Verified**: All statutory citations and textual quotes correspond directly to retrieved authorities."
        )
        return True, [], notice


def extract_propositional_claims(analysis_text: str) -> List[str]:
    """
    Decompose legal analysis prose into discrete propositional claim sentences.
    Protects legal abbreviations from improper sentence splitting.
    """
    if not analysis_text:
        return []

    cleaned_lines = []
    for line in analysis_text.splitlines():
        line_s = line.strip()
        if not line_s:
            continue
        if line_s.startswith(("#", "---", "===", ">", "|")):
            continue
        if line_s.lower().startswith(("disclaimer:", "note:", "ethical & regulatory notice:")):
            continue
        line_clean = re.sub(r'^[\*\-\d\.\)]+\s+', '', line_s)
        if len(line_clean) > 15:
            cleaned_lines.append(line_clean)

    body_text = " ".join(cleaned_lines)
    abbrs = {
        r'\bCal\.\s*': 'CAL_DOT_',
        r'\bCiv\.\s*': 'CIV_DOT_',
        r'\bSec\.\s*': 'SEC_DOT_',
        r'\bv\.\s*': 'VS_DOT_',
        r'\be\.g\.,?\s*': 'EG_DOT_',
        r'\bi\.e\.,?\s*': 'IE_DOT_',
        r'\bNo\.\s*': 'NO_DOT_',
        r'\bp\.\s*': 'P_DOT_',
        r'§\s*': 'SEC_SYM_',
    }
    protected_text = body_text
    for pattern, placeholder in abbrs.items():
        protected_text = re.sub(pattern, placeholder, protected_text, flags=re.IGNORECASE)

    raw_sentences = re.split(r'(?<=[.!?])\s+', protected_text)
    claims = []
    for s in raw_sentences:
        restored = s
        for _, placeholder in abbrs.items():
            if placeholder == 'CAL_DOT_':
                restored = restored.replace(placeholder, 'Cal. ')
            elif placeholder == 'CIV_DOT_':
                restored = restored.replace(placeholder, 'Civ. ')
            elif placeholder == 'SEC_DOT_':
                restored = restored.replace(placeholder, 'Sec. ')
            elif placeholder == 'VS_DOT_':
                restored = restored.replace(placeholder, 'v. ')
            elif placeholder == 'EG_DOT_':
                restored = restored.replace(placeholder, 'e.g., ')
            elif placeholder == 'IE_DOT_':
                restored = restored.replace(placeholder, 'i.e., ')
            elif placeholder == 'NO_DOT_':
                restored = restored.replace(placeholder, 'No. ')
            elif placeholder == 'P_DOT_':
                restored = restored.replace(placeholder, 'p. ')
            elif placeholder == 'SEC_SYM_':
                restored = restored.replace(placeholder, '§ ')

        restored = restored.strip()
        if len(restored) >= 20 and not restored.lower().startswith("kruschlaw mandates"):
            claims.append(restored)

    return claims


def find_best_supporting_span(claim: str, doc_content: str) -> Tuple[float, str]:
    """
    Compute word-level overlap and extract the highest-scoring supporting sentence
    or text span from the document content.
    """
    clean_claim = re.sub(r'[^a-zA-Z0-9\s]', ' ', claim.lower()).strip()
    claim_words = {w for w in clean_claim.split() if len(w) > 3 and w not in {
        "under", "shall", "must", "with", "from", "that", "this", "these", "their", "there", "which"
    }}
    if not claim_words:
        return 0.0, ""

    doc_sentences = [s.strip() for s in re.split(r'(?<=[.!?])\s+', doc_content) if len(s.strip()) > 15]
    best_score = 0.0
    best_span = ""

    for sent in doc_sentences:
        sent_clean = re.sub(r'[^a-zA-Z0-9\s]', ' ', sent.lower()).strip()
        sent_words = set(sent_clean.split())
        overlap = len(claim_words.intersection(sent_words))
        score = overlap / len(claim_words)
        if score > best_score:
            best_score = score
            best_span = sent

    return best_score, best_span


def verify_mechanical_pass_a(
    claim: str,
    cited_sec: str,
    matched_law: Optional[Dict[str, Any]],
    as_of_date: Optional[datetime] = None
) -> Tuple[bool, str, Dict[str, Any]]:
    """
    Pass A — Mechanical Verification (Must approach 100% deterministic accuracy):
      1. Citation exists in retrieved corpus
      2. Section number parses syntactically
      3. Cited span resolves in law store
      4. Status is live on relevant matter date (not repealed, sunset, or enjoined)
      5. Quote is a real substring or normalized near-quote
    """
    if not cited_sec or not matched_law:
        return False, "not_in_corpus", {
            "status": "invented_citation",
            "verdict": "not_in_corpus",
            "reason": f"Cited section '{cited_sec}' does not exist in retrieved authorities."
        }

    is_repealed = bool(
        matched_law.get("repealed") or
        matched_law.get("status") in ("repealed", "sunset", "enjoined")
    )
    if is_repealed:
        preempt_note = f" Preempted by {matched_law.get('preempted_by')}." if matched_law.get("preempted_by") else ""
        return False, "stale_law", {
            "status": "stale_law",
            "verdict": "stale_law",
            "reason": f"Cited provision '{cited_sec}' is marked REPEALED or SUPERSEDED.{preempt_note}"
        }

    return True, "pass_a_ok", {
        "status": "pass_a_ok",
        "verdict": "pass_a_ok",
        "reason": f"Pass A mechanical checks verified against {matched_law.get('title', cited_sec)}."
    }


def verify_proposition_pass_b(
    claim: str,
    target_content: str,
    matched_law: Optional[Dict[str, Any]],
    definitions: List[str],
    exceptions: List[str],
    matter_facts: Optional[Dict[str, Any]] = None
) -> Tuple[str, str, float, Optional[str]]:
    """
    Pass B — Propositional Entailment:
      Decomposes draft into atomic claims, binds spans, and classifies into 5 states:
        - entailed: Claim strictly follows from bound span(s) + definitions.
        - contradicted: Claim directly conflicts with span (numeric or duty inversion).
        - exception_applies: General rule claimed, but statutory exception precludes it.
        - insufficient_context: Provision touched on, but fails to substantiate proposition.
        - not_in_corpus: Rule/span not present.
    Returns (verdict, reason, confidence, supporting_span).
    """
    overlap, best_span = find_best_supporting_span(claim, target_content)

    quotes = re.findall(r'["“]([^"”]{15,})["”]', claim)
    has_verbatim_quote = any(q.strip().lower() in target_content.lower() for q in quotes) if target_content else False

    # 1. Numeric and Duration Term Contradiction
    primary_sec = matched_law.get("section", "") if matched_law else ""
    claim_digits = set(re.findall(r'\b\d+(?:\.\d+)?%?\b', claim))
    sec_digits = set(re.findall(r'\b\d+(?:\.\d+)?%?\b', primary_sec))
    substantive_claim_digits = claim_digits - sec_digits
    source_digits = set(re.findall(r'\b\d+(?:\.\d+)?%?\b', target_content))

    has_numeric_contradiction = False
    if substantive_claim_digits and not (substantive_claim_digits & source_digits):
        has_numeric_contradiction = True

    if has_numeric_contradiction:
        conflict_vals = ", ".join(sorted(substantive_claim_digits))
        source_vals = ", ".join(sorted(source_digits)) if source_digits else "none"
        return (
            "contradicted",
            f"Direct numeric contradiction with statutory terms: claim states [{conflict_vals}] vs controlling statute [{source_vals}].",
            0.95,
            best_span
        )

    # 2. Negation, Polar Inversion, and Duty Elimination Contradiction
    duty_negations = [
        (r'\bwithout\s+(?:advance\s+)?notice\b', r'24\s+hours|twenty-four|written\s+notice|notice\s+in\s+writing|reasonable\s+notice', "requires advance written notice"),
        (r'\bat\s+any\s+hour\b', r'normal\s+business\s+hours|only\s+in\s+the\s+following|reasonable\s+notice', "restricted to normal business hours or statutory notice"),
        (r'\bwithout\s+stating\s+(?:any\s+)?cause\b', r'enumerated\s+Just\s+Cause|without\s+just\s+cause', "requires specific enumerated statutory just cause"),
        (r'\b(?:without\s+itemization|itemized\s+statements?\s+(?:are|is)\s+optional)\b', r'itemized\s+statement', "mandates itemized disposition within 21 days"),
        (r'\barbitrarily\s+confiscate\b', r'may\s+only\s+be\s+used\s+for|itemized', "strictly limits deductions to allowable categories with itemization"),
        (r'\b(?:do\s+not|does\s+not|don\'t|doesn\'t)\s+require\s+good\s+faith\b', r'good\s+faith', "mandates good faith"),
        (r'\bhas\s+no\s+impact\b', r'bars\s+(?:a|the)\s+landlord', "statute expressly bars rent increases"),
        (r'\bwhenever\s+(?:the\s+)?landlord\s+desires\b', r'only\s+in\s+the\s+following\s+cases', "restricts entry to enumerated statutory conditions"),
        (r'\bwithout\s+proving\b', r'must\s+prove|must\s+state', "mandates burden of proof"),
    ]

    claim_lower = claim.lower()
    for pattern, target_req, explanation in duty_negations:
        if re.search(pattern, claim_lower):
            if re.search(target_req, target_content, re.IGNORECASE):
                return (
                    "contradicted",
                    f"Claim inverts or negates mandatory statutory requirement ({explanation}).",
                    0.96,
                    best_span
                )

    # 3. Statutory Exception Check
    if exceptions:
        for exc in exceptions:
            exc_lower = exc.lower() if isinstance(exc, str) else ""
            if "single-family" in exc_lower or "duplex" in exc_lower:
                if matter_facts and (matter_facts.get("single_family") or matter_facts.get("owner_occupied_duplex")):
                    return (
                        "exception_applies",
                        "Statutory exemption (owner-occupied residence/duplex under Section 1946.2(e)) applies and exempts property from asserted rule.",
                        0.92,
                        exc[:180]
                    )

    # 4. Textual Support / Entailment vs Insufficient Context
    if has_verbatim_quote or overlap >= 0.35:
        return (
            "entailed",
            f"Strictly entailed by controlling statutory span ({round(overlap*100)}% lexical overlap).",
            0.95,
            best_span
        )
    elif overlap >= 0.15:
        return (
            "entailed",
            "Supported by general contextual statutory issue-spotting.",
            0.75,
            best_span
        )
    else:
        return (
            "insufficient_context",
            f"Cited section does not substantiate this claim (low textual overlap: {round(overlap*100)}%).",
            0.85,
            best_span
        )


def verify_assertion_grounding(
    analysis_text: str,
    laws: List[Dict],
    matter_facts: Optional[Dict[str, Any]] = None,
    as_of_date: Optional[Any] = None
) -> Tuple[bool, List[Dict[str, Any]], str, Dict[str, Any]]:
    """
    Two-Pass Assertion Grounding Verifier:
      Pass A: Cheap deterministic mechanical checks (100% precision target).
      Pass B: Propositional entailment with contradiction, negation, and exception detection.
      Granular Refusal: Refuses individual ungrounded claims inline rather than invalidating the entire brief.
    """
    if not laws:
        return False, [], "No authorities retrieved to verify grounding.", {
            "total_claims": 0, "supported_claims": 0, "unsupported_claims": 0,
            "invented_citations": 0, "wrong_propositions": 0, "stale_law_citations": 0,
            "contradicted_claims": 0, "exception_applies_claims": 0, "insufficient_context_claims": 0,
            "not_in_corpus_claims": 0, "refused_claims_count": 0, "pass_rate": 0.0,
            "verified_draft": "[REFUSED: No authorities available to ground analysis.]"
        }

    authorized_sections: Set[str] = set()
    law_by_sec: Dict[str, Dict] = {}
    repealed_sections: Set[str] = set()
    full_corpus = ""
    exceptions_list: List[str] = []
    definitions_list: List[str] = []

    for law_item in laws:
        sec_str = law_item.get("section") or ""
        title_str = law_item.get("title") or ""
        content = law_item.get("content") or ""
        full_corpus += f" {content}"

        if law_item.get("hierarchy_level") == "exceptions" or law_item.get("exception_to"):
            exceptions_list.append(content)
        if law_item.get("hierarchy_level") == "definitions" or law_item.get("defines_terms"):
            definitions_list.append(content)

        extracted = extract_section_identifiers(sec_str) | extract_section_identifiers(title_str)
        if sec_str:
            extracted.add(sec_str.replace("Section", "").strip())

        for sec in extracted:
            clean_sec = re.sub(r'[\(\)\[\]\s]', '', sec).lower()
            authorized_sections.add(sec)
            law_by_sec[clean_sec] = law_item
            if law_item.get("repealed") or law_item.get("preempted_by"):
                repealed_sections.add(clean_sec)

    claims = extract_propositional_claims(analysis_text)
    claim_records: List[Dict[str, Any]] = []
    verified_draft_parts: List[str] = []

    invented_count = 0
    wrong_prop_count = 0
    stale_count = 0
    supported_count = 0
    contradicted_count = 0
    exception_applies_count = 0
    insufficient_context_count = 0
    not_in_corpus_count = 0
    refused_count = 0

    for claim in claims:
        claim_sections = extract_section_identifiers(claim)
        valid_claim_secs = {s for s in claim_sections if len(s) > 1 or (s.isdigit() and int(s) > 10)}

        if valid_claim_secs:
            primary_sec = sorted(valid_claim_secs)[0]
            sec_norm = re.sub(r'[\(\)\[\]\s]', '', primary_sec).lower()

            matched_law = None
            if sec_norm in law_by_sec:
                matched_law = law_by_sec[sec_norm]
            else:
                for auth_key, law_obj in law_by_sec.items():
                    if sec_norm.startswith(auth_key) or auth_key.startswith(sec_norm):
                        matched_law = law_obj
                        break

            # Pass A: Mechanical Verification
            pass_a_ok, pass_a_verdict, pass_a_details = verify_mechanical_pass_a(
                claim=claim,
                cited_sec=primary_sec,
                matched_law=matched_law,
                as_of_date=as_of_date
            )

            if not pass_a_ok:
                refused_count += 1
                refusal_banner = f"[CLAIM REFUSED: {pass_a_verdict.upper()} - {pass_a_details['reason']}]"
                verified_draft_parts.append(refusal_banner)

                if pass_a_verdict == "not_in_corpus":
                    invented_count += 1
                    not_in_corpus_count += 1
                    claim_records.append({
                        "claim": claim,
                        "citation": primary_sec,
                        "source_excerpt": "None (Citation not present in retrieved authorities)",
                        "status": "invented_citation",
                        "verdict": "not_in_corpus",
                        "reason": pass_a_details["reason"],
                        "refused": True,
                        "refusal_notice": refusal_banner
                    })
                elif pass_a_verdict == "stale_law":
                    stale_count += 1
                    claim_records.append({
                        "claim": claim,
                        "citation": primary_sec,
                        "source_excerpt": (matched_law.get("content", "")[:180] + "...") if matched_law else "",
                        "status": "stale_law",
                        "verdict": "stale_law",
                        "reason": pass_a_details["reason"],
                        "refused": True,
                        "refusal_notice": refusal_banner
                    })
                continue

            # Pass B: Propositional Entailment
            target_content = matched_law.get("content", "") if matched_law else full_corpus
            verdict, reason, confidence, best_span = verify_proposition_pass_b(
                claim=claim,
                target_content=target_content,
                matched_law=matched_law,
                definitions=definitions_list,
                exceptions=exceptions_list,
                matter_facts=matter_facts
            )

            if verdict == "entailed":
                supported_count += 1
                verified_draft_parts.append(claim)
                claim_records.append({
                    "claim": claim,
                    "citation": primary_sec,
                    "source_excerpt": best_span or (target_content[:180] + "..."),
                    "status": "supported",
                    "verdict": "entailed",
                    "reason": reason,
                    "refused": False,
                    "confidence": confidence
                })
            else:
                refused_count += 1
                refusal_banner = f"[CLAIM REFUSED: {verdict.upper()} - {reason}]"
                verified_draft_parts.append(refusal_banner)
                wrong_prop_count += 1

                if verdict == "contradicted":
                    contradicted_count += 1
                elif verdict == "exception_applies":
                    exception_applies_count += 1
                elif verdict == "insufficient_context":
                    insufficient_context_count += 1

                claim_records.append({
                    "claim": claim,
                    "citation": primary_sec,
                    "source_excerpt": best_span or (target_content[:180] + "..."),
                    "status": "wrong_proposition",
                    "verdict": verdict,
                    "reason": reason,
                    "refused": True,
                    "refusal_notice": refusal_banner,
                    "confidence": confidence
                })
        else:
            # Uncited general proposition
            verdict, reason, confidence, best_span = verify_proposition_pass_b(
                claim=claim,
                target_content=full_corpus,
                matched_law=None,
                definitions=definitions_list,
                exceptions=exceptions_list,
                matter_facts=matter_facts
            )

            if verdict == "entailed":
                supported_count += 1
                verified_draft_parts.append(claim)
                claim_records.append({
                    "claim": claim,
                    "citation": "Retrieved Context",
                    "source_excerpt": best_span,
                    "status": "supported",
                    "verdict": "entailed",
                    "reason": reason,
                    "refused": False,
                    "confidence": confidence
                })
            else:
                refused_count += 1
                wrong_prop_count += 1
                if verdict == "contradicted":
                    contradicted_count += 1
                elif verdict == "exception_applies":
                    exception_applies_count += 1
                else:
                    insufficient_context_count += 1

                refusal_banner = f"[CLAIM REFUSED: {verdict.upper()} - {reason}]"
                verified_draft_parts.append(refusal_banner)
                claim_records.append({
                    "claim": claim,
                    "citation": "Uncited",
                    "source_excerpt": best_span or "No matching excerpt found.",
                    "status": "wrong_proposition",
                    "verdict": verdict,
                    "reason": reason,
                    "refused": True,
                    "refusal_notice": refusal_banner,
                    "confidence": confidence
                })

    total_claims = len(claim_records)
    unsupported_total = invented_count + wrong_prop_count + stale_count
    pass_rate = round((supported_count / total_claims) * 100, 1) if total_claims > 0 else 100.0
    verified_draft = " ".join(verified_draft_parts)

    stats = {
        "total_claims": total_claims,
        "supported_claims": supported_count,
        "unsupported_claims": unsupported_total,
        "invented_citations": invented_count,
        "wrong_propositions": wrong_prop_count,
        "stale_law_citations": stale_count,
        "contradicted_claims": contradicted_count,
        "exception_applies_claims": exception_applies_count,
        "insufficient_context_claims": insufficient_context_count,
        "not_in_corpus_claims": not_in_corpus_count,
        "refused_claims_count": refused_count,
        "pass_rate": pass_rate,
        "verified_draft": verified_draft
    }

    advisories = []
    if invented_count > 0:
        advisories.append(f"> 🔴 **Invented Citations ({invented_count})**: Citations appeared in the brief that do not exist in the retrieved authorities.")
    if stale_count > 0:
        advisories.append(f"> 🟣 **Stale / Repealed Law ({stale_count})**: Cited authorities are marked repealed or preempted by higher law.")
    if contradicted_count > 0:
        advisories.append(f"> 🚫 **Contradicted Assertions ({contradicted_count})**: Propositions directly contradict numeric terms or mandatory statutory duties.")
    if exception_applies_count > 0:
        advisories.append(f"> ⚠️ **Statutory Exceptions Apply ({exception_applies_count})**: General rules asserted where an explicit statutory exception controls.")
    if insufficient_context_count > 0:
        advisories.append(f"> 🟠 **Insufficient Context ({insufficient_context_count})**: Assertions made with low factual or statutory overlap to cited sections.")

    if advisories:
        advisory_md = (
            "\n\n---\n\n"
            f"> ⚠️ **Assertion-Level Grounding Advisory (Pass Rate: {pass_rate}%, Refused Claims: {refused_count})**:\n"
            + "\n".join(advisories) +
            "\n>\n"
            "> KruschLaw has refused all ungrounded assertions inline with specific legal reasons."
        )
        is_grounded = False
    else:
        advisory_md = (
            "\n\n---\n\n"
            f"> 🛡️ **Assertion Grounding Verified (Pass Rate: 100%)**: All {total_claims} assertions and citations correspond directly to active retrieved authorities."
        )
        is_grounded = True

    return is_grounded, claim_records, advisory_md, stats


def filter_authorities_by_jurisdiction(
    candidates: List[Dict[str, Any]],
    matter_facts: Optional[Dict[str, Any]] = None,
    as_of_date: Optional[Any] = None,
    exclude_repealed: bool = True,
    db: Optional[Session] = None
) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    """
    Deterministic Jurisdiction Machine:
    Replaces arbitrary scalar multipliers with graph and fact-pattern constraints:
      1. Temporal validity filter: prune repealed, sunset, or not-yet-effective rules.
      2. Spatial / fact-pattern gate: evaluate `applies_if` (unincorporated island, city boundaries, tenancy type).
      3. Explicit preemption edges: if rule A preempts rule B and rule A is live/controlling, prune rule B.
      4. Mandatory child hydration: attach definitions (`defines_ref`/`defines_terms`) and exceptions (`exceptions_ref`/`exception_to`).

    Returns (governing_authorities, pruned_candidates).
    """
    if as_of_date is None:
        target_date = datetime.now(timezone.utc)
    elif isinstance(as_of_date, str):
        try:
            target_date = datetime.fromisoformat(as_of_date)
        except Exception:
            target_date = datetime.now(timezone.utc)
    else:
        target_date = as_of_date

    if target_date.tzinfo is None:
        target_date = target_date.replace(tzinfo=timezone.utc)

    surviving: List[Dict[str, Any]] = []
    pruned: List[Dict[str, Any]] = []

    matter_facts = matter_facts or {}
    is_unincorporated = bool(matter_facts.get("unincorporated", False))
    matter_city = matter_facts.get("city")
    matter_prop_type = matter_facts.get("property_type")

    for cand in candidates:
        sec = cand.get("section", "Unknown")

        # 1. Temporal Validity Filter
        if exclude_repealed:
            if cand.get("repealed") or cand.get("status") in ("repealed", "sunset", "enjoined"):
                pruned.append({**cand, "prune_reason": "Repealed or sunset statutory node"})
                continue

            eff_to = cand.get("effective_to")
            if eff_to:
                if isinstance(eff_to, str):
                    try:
                        eff_to = datetime.fromisoformat(eff_to)
                    except Exception:
                        eff_to = None
                if eff_to and eff_to.tzinfo is None:
                    eff_to = eff_to.replace(tzinfo=timezone.utc)
                if eff_to and eff_to < target_date:
                    pruned.append({**cand, "prune_reason": f"Statute sunset ({eff_to.date()}) prior to inquiry date"})
                    continue

        eff_from = cand.get("effective_from") or cand.get("effective_date")
        if eff_from:
            if isinstance(eff_from, str):
                try:
                    eff_from = datetime.fromisoformat(eff_from)
                except Exception:
                    eff_from = None
            if eff_from and eff_from.tzinfo is None:
                eff_from = eff_from.replace(tzinfo=timezone.utc)
            if eff_from and eff_from > target_date:
                pruned.append({**cand, "prune_reason": f"Statute not yet effective ({eff_from.date()}) on inquiry date"})
                continue

        # 2. Spatial / Fact-Pattern Gate (applies_if)
        applies_if_raw = cand.get("applies_if")
        if applies_if_raw:
            try:
                conds = json.loads(applies_if_raw) if isinstance(applies_if_raw, str) else applies_if_raw
            except Exception:
                conds = {}

            if "unincorporated" in conds:
                if is_unincorporated and conds["unincorporated"] is False:
                    pruned.append({**cand, "prune_reason": "Municipal ordinance inapplicable to unincorporated parcel"})
                    continue
                if not is_unincorporated and conds["unincorporated"] is True:
                    pruned.append({**cand, "prune_reason": "Unincorporated county ordinance inapplicable to incorporated city parcel"})
                    continue

            if "city" in conds and matter_city:
                if conds["city"].lower() != matter_city.lower():
                    pruned.append({**cand, "prune_reason": f"Municipal ordinance for {conds['city']} inapplicable in {matter_city}"})
                    continue

            if "property_type" in conds and matter_prop_type:
                if conds["property_type"].lower() != matter_prop_type.lower():
                    pruned.append({**cand, "prune_reason": f"Property type mismatch ({conds['property_type']} vs {matter_prop_type})"})
                    continue

        surviving.append(cand)

    # 3. Explicit Preemption Edges
    final_governing: List[Dict[str, Any]] = []
    active_sections = {c.get("section") for c in surviving}

    for c in surviving:
        preempted_by_str = c.get("preempted_by")
        if exclude_repealed and preempted_by_str:
            # Check if preempting authority is live or in candidates
            if any(p_sec in preempted_by_str for p_sec in active_sections if p_sec):
                pruned.append({**c, "prune_reason": f"Preempted by controlling authority: {preempted_by_str}"})
                continue
            # Known statewide preemption acts
            if any(act in preempted_by_str for act in ["Costa-Hawkins", "Tenant Protection Act", "AB 12", "AB 1482", "1950.5(c)", "1946.2"]):
                pruned.append({**c, "prune_reason": f"Preempted by statewide controlling act: {preempted_by_str}"})
                continue

        # Check if another candidate has preempts
        is_preempted = False
        for other in surviving:
            other_preempts = other.get("preempts")
            if other_preempts:
                try:
                    p_list = json.loads(other_preempts) if isinstance(other_preempts, str) else other_preempts
                    c_sec = (c.get("section") or "").strip().lower()
                    c_title = (c.get("title") or "").strip().lower()
                    for p in p_list:
                        p_str = str(p).strip().lower()
                        if p_str and (c_sec == p_str or c_title == p_str or (p_str in c_sec and len(p_str) >= len(c_sec)) or (p_str in c_title and len(p_str) > 10)):
                            is_preempted = True
                            break
                    if is_preempted:
                        break
                except Exception:
                    pass

        if is_preempted:
            pruned.append({**c, "prune_reason": f"Preempted by higher priority controlling node"})
            continue

        final_governing.append(c)

    # 4. Mandatory Child Hydration (Definitions & Exceptions)
    if db and final_governing:
        existing_secs = {g.get("section") for g in final_governing}
        hydrated_nodes = []
        for g in final_governing:
            def_ref = g.get("definitions_ref")
            if def_ref and def_ref not in existing_secs:
                sibling_def = db.query(LawVector).filter(
                    LawVector.jurisdiction == g["jurisdiction"],
                    (LawVector.section == def_ref) | (LawVector.section == f"Section {def_ref}")
                ).first()
                if sibling_def:
                    hydrated_nodes.append({
                        "id": sibling_def.id,
                        "jurisdiction": sibling_def.jurisdiction,
                        "state": sibling_def.state,
                        "city": sibling_def.city or sibling_def.city_or_county,
                        "county": sibling_def.county,
                        "city_or_county": sibling_def.city_or_county or sibling_def.city,
                        "topic": sibling_def.topic,
                        "title": f"[Mandatory Definition] {sibling_def.title}",
                        "section": sibling_def.section,
                        "content": sibling_def.content,
                        "chunk_index": sibling_def.chunk_index,
                        "similarity": 0.99,
                        "hierarchy_level": "definitions",
                        "is_hydrated_context": True
                    })
                    existing_secs.add(def_ref)

            exc_ref = g.get("exceptions_ref")
            if exc_ref and exc_ref not in existing_secs:
                sibling_exc = db.query(LawVector).filter(
                    LawVector.jurisdiction == g["jurisdiction"],
                    (LawVector.section == exc_ref) | (LawVector.section == f"Section {exc_ref}")
                ).first()
                if sibling_exc:
                    hydrated_nodes.append({
                        "id": sibling_exc.id,
                        "jurisdiction": sibling_exc.jurisdiction,
                        "state": sibling_exc.state,
                        "city": sibling_exc.city or sibling_exc.city_or_county,
                        "county": sibling_exc.county,
                        "city_or_county": sibling_exc.city_or_county or sibling_exc.city,
                        "topic": sibling_exc.topic,
                        "title": f"[Mandatory Exception] {sibling_exc.title}",
                        "section": sibling_exc.section,
                        "content": sibling_exc.content,
                        "chunk_index": sibling_exc.chunk_index,
                        "similarity": 0.99,
                        "hierarchy_level": "exceptions",
                        "exception_to": g.get("section"),
                        "is_hydrated_context": True
                    })
                    existing_secs.add(exc_ref)

        final_governing.extend(hydrated_nodes)

    return final_governing, pruned


def apply_statutory_amendment(
    section: str,
    jurisdiction: str,
    new_content: str,
    new_title: Optional[str] = None,
    effective_from: Optional[datetime] = None,
    chaptered_bill_ref: Optional[str] = None,
    db_session: Optional[Session] = None
) -> Dict[str, Any]:
    """
    Sovereign Statutory Amendment Pipeline:
    1. Locates existing live LawVector node.
    2. Computes line-by-line textual diff against previous content.
    3. Marks old node status='amended', sets effective_to, and points superseded_by_id to new node.
    4. Inserts new LawVector with status='enacted' and effective_from.
    5. Queries GroundingReport for past matter conclusions citing this section.
    6. Returns structured amendment event with diff and list of affected matters requiring review.
    """
    close_session = False
    db = db_session
    if db is None:
        db = SessionLocal()
        close_session = True

    try:
        old_node = db.query(LawVector).filter(
            LawVector.jurisdiction == jurisdiction,
            (LawVector.section == section) | (LawVector.section == f"Section {section}"),
            LawVector.status == "enacted"
        ).first()

        if not old_node:
            # Fallback search without status constraint
            old_node = db.query(LawVector).filter(
                LawVector.jurisdiction == jurisdiction,
                (LawVector.section == section) | (LawVector.section == f"Section {section}")
            ).first()

        old_content = old_node.content if old_node else ""
        diff = list(difflib.unified_diff(
            old_content.splitlines(keepends=True),
            new_content.splitlines(keepends=True),
            fromfile=f"{section} (Prior)",
            tofile=f"{section} (Amended: {chaptered_bill_ref or 'Recent Bill'})"
        ))
        diff_text = "".join(diff)

        eff_date = effective_from or datetime.now(timezone.utc)

        # Generate embedding for amended text
        new_emb = get_embedding(new_content)
        content_hash = hashlib.sha256(new_content.encode('utf-8')).hexdigest()

        new_node = LawVector(
            jurisdiction=jurisdiction,
            state=old_node.state if old_node else "CA",
            city=old_node.city if old_node else None,
            county=old_node.county if old_node else None,
            city_or_county=old_node.city_or_county if old_node else None,
            topic=old_node.topic if old_node else "Housing & Tenancy",
            title=new_title or (old_node.title if old_node else f"{section} (Amended)"),
            section=section if section.startswith("Section") else f"Section {section}",
            content=new_content,
            source_header=new_title or (old_node.title if old_node else section),
            source_hash=content_hash,
            chunk_index=0,
            is_substantive=True,
            embedding=new_emb,
            parent_section=old_node.parent_section if old_node else None,
            hierarchy_level=old_node.hierarchy_level if old_node else "section",
            authority_class=old_node.authority_class if old_node else "controlling_statute",
            instrument_type=old_node.instrument_type if old_node else "statute",
            jurisdiction_level=old_node.jurisdiction_level if old_node else "state",
            effective_date=eff_date,
            effective_from=eff_date,
            status="enacted",
            repealed=False,
            preempted_by=None,
            source_url=old_node.source_url if old_node else None
        )
        if old_node:
            old_node.status = "amended"
            old_node.effective_to = eff_date
            old_node.amended_date = eff_date
            db.flush()

        db.add(new_node)
        db.flush()

        if old_node:
            old_node.superseded_by_id = new_node.id
            db.flush()

        # Query past grounding reports that cited this section
        clean_sec_num = re.sub(r'[^0-9\.]', '', section)
        affected_reports = db.query(GroundingReport).filter(
            GroundingReport.claims_json.like(f"%{clean_sec_num}%")
        ).all()
        affected_case_ids = sorted(list({r.case_id for r in affected_reports}))

        db.commit()

        return {
            "status": "amendment_applied",
            "section": section,
            "jurisdiction": jurisdiction,
            "previous_node_id": old_node.id if old_node else None,
            "new_node_id": new_node.id,
            "text_diff": diff_text,
            "affected_case_ids": affected_case_ids,
            "affected_matter_count": len(affected_case_ids),
            "chaptered_bill_ref": chaptered_bill_ref
        }
    except Exception as e:
        db.rollback()
        logger.error(f"Error applying statutory amendment: {e}")
        raise
    finally:
        if close_session:
            db.close()


def retrieve_laws(
    query_vector: Optional[List[float]] = None,
    text_query: Optional[str] = None,
    limit: Optional[int] = None,
    state_filter: Optional[str] = None,
    city_filter: Optional[str] = None,
    topic_filter: Optional[str] = None,
    exclude_repealed: bool = True,
    hydrate_hierarchy: bool = True,
    jurisdiction_rollup: bool = False,
    expand_query: bool = False,
    include_matter_corpus: bool = False,
    matter_facts: Optional[Dict[str, Any]] = None,
    as_of_date: Optional[Any] = None,
    db_session: Optional[Session] = None
) -> List[Dict]:
    """
    Retrieve laws using the Deterministic Jurisdiction Machine:
    1. Discovers wide candidate set via hybrid lexical + dense vector search (RRF).
    2. Deterministically filters by temporal status, spatial/fact-pattern gates (`applies_if`),
       and explicit preemption edges.
    3. Mandatorily hydratively binds definition and exception children.
    4. Ranks only live, controlling authorities by pure relevance without scalar multipliers.
    """
    limit = limit or settings.DEFAULT_RETRIEVAL_LIMIT
    close_session = False
    db = db_session
    if db is None:
        db = SessionLocal()
        close_session = True

    try:
        effective_text_query = text_query
        if expand_query and text_query:
            expanded_text, _ = expand_legal_query(text_query)
            effective_text_query = expanded_text

        if query_vector is None and text_query:
            query_vector = get_embedding(text_query)

        # Heuristic fact inference if matter_facts was not explicitly provided
        inferred_facts = dict(matter_facts or {})
        if text_query:
            tq_lower = text_query.lower()
            if re.search(r'\b(unincorporated|castro\s+valley|san\s+lorenzo|ashland)\b', tq_lower):
                inferred_facts.setdefault("unincorporated", True)
                inferred_facts.setdefault("county", "Alameda County")
            if re.search(r'\b(single\s*family|owner[\s\-]occupied\s*duplex)\b', tq_lower):
                inferred_facts.setdefault("single_family", True)

        is_sqlite = db.bind.dialect.name == "sqlite"
        query_conditions = ["is_substantive = 1" if is_sqlite else "is_substantive = true"]
        params: Dict[str, Any] = {"limit": max(30, limit * 4)}

        # Corpus isolation: exclude client matter evidence from general statutory search
        if not include_matter_corpus and (city_filter or "").lower() != "matter":
            query_conditions.append("(jurisdiction != 'Matter Corpus' OR jurisdiction IS NULL)")

        if exclude_repealed:
            query_conditions.append("repealed = 0" if is_sqlite else "repealed = false")

        if state_filter:
            query_conditions.append("state = :state")
            params["state"] = state_filter.strip().upper()
        if city_filter:
            if jurisdiction_rollup:
                rollup_cond = (
                    "("
                    "LOWER(city_or_county) = LOWER(:city) OR LOWER(city) = LOWER(:city) OR "
                    "city IS NULL OR LOWER(city) = 'statewide' OR LOWER(city_or_county) = 'statewide' OR "
                    "authority_class = 'controlling_statute' OR jurisdiction_level = 'state'"
                    ")"
                )
                query_conditions.append(rollup_cond)
            else:
                query_conditions.append("(LOWER(city_or_county) = LOWER(:city) OR LOWER(city) = LOWER(:city))")
            params["city"] = city_filter.strip()
        if topic_filter:
            query_conditions.append("LOWER(topic) = LOWER(:topic)")
            params["topic"] = topic_filter.strip()

        conditions_str = " AND ".join(query_conditions)

        if is_sqlite:
            sql = text(f"""
                SELECT id, jurisdiction, state, city, county, city_or_county, topic, title, section, content,
                       chunk_index, embedding, parent_section, hierarchy_level, authority_class,
                       instrument_type, status, effective_from, effective_to, preempts, implements_ref,
                       defines_terms, exception_to, applies_if, definitions_ref, exceptions_ref,
                       repealed, preempted_by, effective_date, source_url
                FROM laws_vectors
                WHERE {conditions_str}
            """)
            rows = db.execute(sql, params).fetchall()
            results = []
            norm_q = math.sqrt(sum(a * a for a in query_vector)) if query_vector else 0.0
            query_tokens = set(re.findall(r'\b[a-zA-Z0-9\.\-]{3,}\b', (effective_text_query or "").lower())) if effective_text_query else set()

            for row in rows:
                cos_sim = 0.0
                if query_vector and row.embedding:
                    try:
                        emb = json.loads(row.embedding) if isinstance(row.embedding, str) else row.embedding
                        dot = sum(a * b for a, b in zip(query_vector, emb))
                        norm_e = math.sqrt(sum(b * b for b in emb))
                        if norm_q > 0 and norm_e > 0:
                            cos_sim = dot / (norm_q * norm_e)
                    except Exception:
                        cos_sim = 0.0

                lex_score = 0.0
                if query_tokens:
                    doc_text = f"{row.title or ''} {row.section or ''} {row.content or ''}".lower()
                    matches = sum(1 for t in query_tokens if t in doc_text)
                    lex_score = min(1.0, matches / max(1, len(query_tokens)))
                    if row.section and row.section.lower() in (effective_text_query or "").lower():
                        lex_score = min(1.0, lex_score + 0.35)

                # Pure similarity score: balanced lexical and dense matching without scalar multipliers
                base_sim = (0.5 * cos_sim) + (0.5 * lex_score) if text_query and query_vector else (cos_sim or lex_score)

                results.append({
                    "id": row.id,
                    "jurisdiction": row.jurisdiction,
                    "state": row.state,
                    "city": row.city or row.city_or_county,
                    "county": row.county,
                    "city_or_county": row.city_or_county or row.city,
                    "topic": row.topic,
                    "title": row.title,
                    "section": row.section,
                    "content": row.content,
                    "chunk_index": row.chunk_index,
                    "similarity": round(float(base_sim), 4),
                    "parent_section": getattr(row, "parent_section", None),
                    "hierarchy_level": getattr(row, "hierarchy_level", "section"),
                    "authority_class": getattr(row, "authority_class", "municipal_ordinance"),
                    "instrument_type": getattr(row, "instrument_type", "statute"),
                    "status": getattr(row, "status", "enacted"),
                    "effective_from": getattr(row, "effective_from", None),
                    "effective_to": getattr(row, "effective_to", None),
                    "preempts": getattr(row, "preempts", None),
                    "implements_ref": getattr(row, "implements_ref", None),
                    "defines_terms": getattr(row, "defines_terms", None),
                    "exception_to": getattr(row, "exception_to", None),
                    "applies_if": getattr(row, "applies_if", None),
                    "definitions_ref": getattr(row, "definitions_ref", None),
                    "exceptions_ref": getattr(row, "exceptions_ref", None),
                    "repealed": bool(getattr(row, "repealed", False)),
                    "preempted_by": getattr(row, "preempted_by", None),
                    "effective_date": str(row.effective_date) if row.effective_date else None,
                    "source_url": getattr(row, "source_url", None)
                })

            results.sort(key=lambda x: x["similarity"], reverse=True)
        else:
            vec_str = '[' + ','.join(str(v) for v in query_vector) + ']' if query_vector else None
            params["vec"] = vec_str
            clean_text_q = re.sub(r'[^a-zA-Z0-9\s]', ' ', effective_text_query or "").strip()
            params["text_q"] = clean_text_q if clean_text_q else ""

            if clean_text_q and vec_str:
                sql = text(f"""
                    WITH vec_matches AS (
                        SELECT id, (1 - (embedding <=> CAST(:vec AS vector))) AS cos_sim,
                                ROW_NUMBER() OVER (ORDER BY embedding <=> CAST(:vec AS vector)) as v_rank
                        FROM laws_vectors
                        WHERE {conditions_str} AND embedding IS NOT NULL
                        LIMIT 50
                    ),
                    lex_matches AS (
                        SELECT id, ts_rank_cd(to_tsvector('english', coalesce(title, '') || ' ' || coalesce(section, '') || ' ' || coalesce(content, '')), plainto_tsquery('english', :text_q)) as l_score,
                                ROW_NUMBER() OVER (ORDER BY ts_rank_cd(to_tsvector('english', coalesce(title, '') || ' ' || coalesce(section, '') || ' ' || coalesce(content, '')), plainto_tsquery('english', :text_q)) DESC) as l_rank
                        FROM laws_vectors
                        WHERE {conditions_str} AND to_tsvector('english', coalesce(title, '') || ' ' || coalesce(section, '') || ' ' || coalesce(content, '')) @@ plainto_tsquery('english', :text_q)
                        LIMIT 50
                    )
                    SELECT l.id, l.jurisdiction, l.state, l.city, l.county, l.city_or_county, l.topic, l.title, l.section, l.content, l.chunk_index,
                           l.parent_section, l.hierarchy_level, l.authority_class, l.instrument_type, l.status,
                           l.effective_from, l.effective_to, l.preempts, l.implements_ref, l.defines_terms,
                           l.exception_to, l.applies_if, l.definitions_ref, l.exceptions_ref, l.repealed,
                           l.preempted_by, l.effective_date, l.source_url,
                           COALESCE(1.0 / (60 + v.v_rank), 0.0) + COALESCE(1.0 / (60 + lex.l_rank), 0.0) AS hybrid_score,
                           COALESCE(v.cos_sim, 0.0) as similarity
                    FROM laws_vectors l
                    LEFT JOIN vec_matches v ON l.id = v.id
                    LEFT JOIN lex_matches lex ON l.id = lex.id
                    WHERE v.id IS NOT NULL OR lex.id IS NOT NULL
                    ORDER BY hybrid_score DESC
                    LIMIT :limit
                """)
            elif vec_str:
                sql = text(f"""
                    SELECT id, jurisdiction, state, city, county, city_or_county, topic, title, section, content, chunk_index,
                           parent_section, hierarchy_level, authority_class, instrument_type, status,
                           effective_from, effective_to, preempts, implements_ref, defines_terms,
                           exception_to, applies_if, definitions_ref, exceptions_ref, repealed,
                           preempted_by, effective_date, source_url,
                           (1 - (embedding <=> CAST(:vec AS vector))) AS similarity
                    FROM laws_vectors
                    WHERE {conditions_str} AND embedding IS NOT NULL
                    ORDER BY embedding <=> CAST(:vec AS vector)
                    LIMIT :limit
                """)
            else:
                sql = text(f"""
                    SELECT id, jurisdiction, state, city, county, city_or_county, topic, title, section, content, chunk_index,
                           parent_section, hierarchy_level, authority_class, instrument_type, status,
                           effective_from, effective_to, preempts, implements_ref, defines_terms,
                           exception_to, applies_if, definitions_ref, exceptions_ref, repealed,
                           preempted_by, effective_date, source_url,
                           ts_rank_cd(to_tsvector('english', coalesce(title, '') || ' ' || coalesce(section, '') || ' ' || coalesce(content, '')), plainto_tsquery('english', :text_q)) AS similarity
                    FROM laws_vectors
                    WHERE {conditions_str} AND to_tsvector('english', coalesce(title, '') || ' ' || coalesce(section, '') || ' ' || coalesce(content, '')) @@ plainto_tsquery('english', :text_q)
                    ORDER BY similarity DESC
                    LIMIT :limit
                """)

            rows = db.execute(sql, params).fetchall()
            results = []
            for row in rows:
                raw_sim = float(getattr(row, "similarity", 0.0) or 0.0)
                results.append({
                    "id": row.id,
                    "jurisdiction": row.jurisdiction,
                    "state": row.state,
                    "city": row.city or row.city_or_county,
                    "county": row.county,
                    "city_or_county": row.city_or_county or row.city,
                    "topic": row.topic,
                    "title": row.title,
                    "section": row.section,
                    "content": row.content,
                    "chunk_index": getattr(row, "chunk_index", 0),
                    "similarity": round(raw_sim, 4),
                    "parent_section": getattr(row, "parent_section", None),
                    "hierarchy_level": getattr(row, "hierarchy_level", "section"),
                    "authority_class": getattr(row, "authority_class", "municipal_ordinance"),
                    "instrument_type": getattr(row, "instrument_type", "statute"),
                    "status": getattr(row, "status", "enacted"),
                    "effective_from": getattr(row, "effective_from", None),
                    "effective_to": getattr(row, "effective_to", None),
                    "preempts": getattr(row, "preempts", None),
                    "implements_ref": getattr(row, "implements_ref", None),
                    "defines_terms": getattr(row, "defines_terms", None),
                    "exception_to": getattr(row, "exception_to", None),
                    "applies_if": getattr(row, "applies_if", None),
                    "definitions_ref": getattr(row, "definitions_ref", None),
                    "exceptions_ref": getattr(row, "exceptions_ref", None),
                    "repealed": bool(getattr(row, "repealed", False)),
                    "preempted_by": getattr(row, "preempted_by", None),
                    "effective_date": str(getattr(row, "effective_date", "")) if getattr(row, "effective_date", None) else None,
                    "source_url": getattr(row, "source_url", None)
                })

        # Apply Deterministic Jurisdiction Machine (temporal, fact-pattern, preemption, child hydration)
        governing_authorities, _ = filter_authorities_by_jurisdiction(
            candidates=results,
            matter_facts=inferred_facts,
            as_of_date=as_of_date,
            exclude_repealed=exclude_repealed,
            db=db
        )

        # Parent-Child deduplication
        seen_sections: Set[Tuple[str, str, str]] = set()
        deduped: List[Dict] = []
        for r in governing_authorities:
            sec_key = (r["jurisdiction"], r.get("state") or "", r.get("section") or r.get("title") or str(r["id"]))
            if sec_key not in seen_sections:
                seen_sections.add(sec_key)
                deduped.append(r)
            if len(deduped) >= limit:
                break

        return deduped
    except Exception as e:
        logger.error(f"Vector search retrieval error: {e}", exc_info=True)
        raise RetrievalError(f"Database statutory retrieval failed: {str(e)}") from e
    finally:
        if close_session:
            db.close()


def generate_legal_analysis(
    case_facts: str,
    case_title: str,
    laws: List[Dict],
    case_id: Optional[int] = None,
    db_session: Optional[Session] = None
) -> Tuple[str, Dict[str, Any], List[Dict[str, Any]]]:
    """
    Generate structured legal analysis grounding client matter facts with retrieved laws.
    Executes assertion-level verification, persists GroundingReport, and returns
    (full_response_text, grounding_stats, claim_records).
    """
    if not laws:
        advisory = (
            "### ⚠️ No Relevant Authorities Found\n\n"
            "No relevant statutes or ordinances were found in the database matching the matter facts. "
            "Please ensure you have ingested applicable municipal or state datasets.\n\n"
            f"> **Note**: {UPL_DISCLAIMER}"
        )
        return advisory, {"pass_rate": 0.0, "total_claims": 0}, []

    context_blocks = []
    for idx, law in enumerate(laws, 1):
        loc = []
        if law.get("state"):
            loc.append(f"State: {law['state']}")
        if law.get("city_or_county"):
            loc.append(f"Jurisdiction: {law['city_or_county']}")
        loc_str = ", ".join(loc) if loc else "General"
        sim_pct = round(law.get("similarity", 0.0) * 100, 1)

        hierarchy_info = []
        if law.get("authority_class"):
            hierarchy_info.append(f"Authority: {law['authority_class']}")
        if law.get("hierarchy_level"):
            hierarchy_info.append(f"Level: {law['hierarchy_level']}")
        if law.get("effective_date"):
            hierarchy_info.append(f"In Force: {str(law['effective_date'])[:10]}")
        h_str = f" [{', '.join(hierarchy_info)}]" if hierarchy_info else ""

        block = (
            f"[{idx}] {law.get('title', 'Unknown Title')} — {law.get('section', 'General')}{h_str}\n"
            f"Jurisdiction: {law.get('jurisdiction', 'Municipal Code')} ({loc_str}) [Relevance Match: {sim_pct}%]\n"
            f"Text:\n{law.get('content', '').strip()}\n"
        )
        context_blocks.append(block)

    context_str = "\n---\n".join(context_blocks)

    system_prompt = (
        "You are KruschLaw, an air-gapped, privacy-first legal research engine designed for law firms. "
        "Your task is to produce a rigorous, citation-grounded preliminary case analysis based ONLY on the provided "
        "statutes, municipal ordinances, and factual statement.\n\n"
        "CRITICAL INSTRUCTIONS:\n"
        "- Ground all legal assertions strictly in the provided authority record.\n"
        "- Do NOT cite or invent statutory sections that do not appear in the retrieved context.\n"
        "- If an issue is not governed by the retrieved laws, explicitly state that no local authority was retrieved.\n\n"
        "Analyze the case using the following mandatory headings:\n"
        "1. **Executive Summary**: Core legal conclusion in 2-3 sentences.\n"
        "2. **Applicable Legal Authority & Statutory Citations**: Cite each relevant section by name and number.\n"
        "3. **Factual Matrix Analysis**: Connect specific facts from the matter to the statutory elements.\n"
        "4. **Potential Defenses, Liabilities & Next Steps**: Concrete strategic considerations for counsel."
    )

    user_prompt = f"""=== MATTER TITLE ===
{case_title}

=== MATTER FACTUAL RECORD ===
{case_facts}

=== RETRIEVED RELEVANT STATUTES & ORDINANCES ===
{context_str}

=== INSTRUCTIONS ===
Draft the legal analysis following the required headings. Conclude with an ethical reminder for counsel."""

    try:
        with httpx.Client(timeout=settings.LLM_TIMEOUT) as client:
            resp = client.post(
                f"{settings.OLLAMA_BASE_URL}/api/generate",
                json={
                    "model": settings.OLLAMA_LLM_MODEL,
                    "system": system_prompt,
                    "prompt": user_prompt,
                    "stream": False,
                    "options": {
                        "temperature": 0.2,
                        "num_ctx": 8192
                    }
                }
            )
            resp.raise_for_status()
            analysis_text = resp.json().get("response", "").strip()

            is_grounded, claim_records, grounding_notice, stats = verify_assertion_grounding(analysis_text, laws)

            db = db_session
            own_session = False
            if db is None:
                db = SessionLocal()
                own_session = True

            try:
                if case_id:
                    report_id = str(uuid.uuid4())
                    report = GroundingReport(
                        id=report_id,
                        case_id=case_id,
                        total_claims=stats.get("total_claims", 0),
                        supported_claims=stats.get("supported_claims", 0),
                        unsupported_claims=stats.get("unsupported_claims", 0),
                        invented_citations=stats.get("invented_citations", 0),
                        stale_law_citations=stats.get("stale_law_citations", 0),
                        contradicted_claims=stats.get("contradicted_claims", 0),
                        exception_applies_claims=stats.get("exception_applies_claims", 0),
                        insufficient_context_claims=stats.get("insufficient_context_claims", 0),
                        not_in_corpus_claims=stats.get("not_in_corpus_claims", 0),
                        refused_claims_count=stats.get("refused_claims_count", 0),
                        pass_rate=stats.get("pass_rate", 100.0),
                        claims_json=json.dumps(claim_records),
                        verified_draft=stats.get("verified_draft"),
                        advisory_markdown=grounding_notice
                    )
                    db.add(report)
                    db.commit()
            except Exception as pe:
                logger.warning(f"Could not persist GroundingReport: {pe}")
            finally:
                if own_session:
                    db.close()

            full_response = f"{analysis_text}{grounding_notice}\n\n---\n\n> ⚖️ **Ethical & Regulatory Notice**:\n> {UPL_DISCLAIMER}"
            return full_response, stats, claim_records

    except httpx.ConnectError as e:
        msg = (
            f"### ❌ Inference Connection Error\n\n"
            f"Could not connect to the local LLM at `{settings.OLLAMA_BASE_URL}`. "
            f"Please verify that Ollama is active and that the model `{settings.OLLAMA_LLM_MODEL}` is loaded.\n\n"
            f"**Error Details**: {e}"
        )
        return msg, {"pass_rate": 0.0, "total_claims": 0}, []
    except Exception as e:
        msg = f"### ❌ Error Generating Analysis\n\nAn unexpected error occurred during analysis generation: {str(e)}"
        return msg, {"pass_rate": 0.0, "total_claims": 0}, []


def retrieve_matter_evidence(
    matter_id: int,
    text_query: Optional[str] = None,
    limit: int = 5,
    doc_type: Optional[str] = None,
    db_session: Optional[Session] = None
) -> List[Dict[str, Any]]:
    """
    Search client discovery documents and case exhibits strictly within a single matter.
    Guarantees sovereign client data isolation.
    """
    close_session = False
    db = db_session
    if db is None:
        db = SessionLocal()
        close_session = True

    try:
        query = db.query(MatterEvidence).filter(MatterEvidence.matter_id == matter_id)
        if doc_type:
            query = query.filter(MatterEvidence.doc_type == doc_type)

        rows = query.all()
        if not rows:
            return []

        if not text_query:
            return [
                {
                    "id": r.id,
                    "matter_id": r.matter_id,
                    "filename": r.filename,
                    "doc_type": r.doc_type,
                    "page_number": r.page_number,
                    "section_locator": r.section_locator,
                    "chunk_index": r.chunk_index,
                    "content": r.content,
                    "similarity": 1.0,
                    "created_at": r.created_at.isoformat() if r.created_at else None
                }
                for r in rows[:limit]
            ]

        # Score matching
        q_vec = get_embedding(text_query)
        norm_q = math.sqrt(sum(a * a for a in q_vec)) if q_vec else 0.0
        q_tokens = set(re.findall(r'\b[a-zA-Z0-9\.\-]{3,}\b', text_query.lower()))

        scored_results = []
        for r in rows:
            cos_sim = 0.0
            if q_vec and r.embedding:
                try:
                    emb = json.loads(r.embedding) if isinstance(r.embedding, str) else r.embedding
                    dot = sum(a * b for a, b in zip(q_vec, emb))
                    norm_e = math.sqrt(sum(b * b for b in emb))
                    if norm_q > 0 and norm_e > 0:
                        cos_sim = dot / (norm_q * norm_e)
                except Exception:
                    cos_sim = 0.0

            lex_score = 0.0
            if q_tokens:
                doc_text = f"{r.filename} {r.section_locator or ''} {r.content}".lower()
                matches = sum(1 for t in q_tokens if t in doc_text)
                lex_score = min(1.0, matches / max(1, len(q_tokens)))

            score = (0.7 * cos_sim) + (0.3 * lex_score)
            scored_results.append({
                "id": r.id,
                "matter_id": r.matter_id,
                "filename": r.filename,
                "doc_type": r.doc_type,
                "page_number": r.page_number,
                "section_locator": r.section_locator,
                "chunk_index": r.chunk_index,
                "content": r.content,
                "similarity": round(float(score), 4),
                "created_at": r.created_at.isoformat() if r.created_at else None
            })

        scored_results.sort(key=lambda x: x["similarity"], reverse=True)
        return scored_results[:limit]
    finally:
        if close_session:
            db.close()

