import re
import json
import math
import logging
import httpx
from typing import List, Dict, Optional, Tuple, Set
from sqlalchemy import text
from sqlalchemy.orm import Session

from .config import settings
from .db import SessionLocal

logger = logging.getLogger("kruschlaw.rag")

UPL_DISCLAIMER = (
    "DISCLAIMER: This analysis was generated by KruschLaw, an offline, air-gapped AI research engine. "
    "This material is provided strictly for exploratory legal research and preliminary issue-spotting. "
    "It does NOT constitute legal advice, formal representation, or an attorney-client relationship. "
    "A licensed attorney admitted to practice in the relevant jurisdiction must independently verify "
    "all cited statutes, local ordinances, and analytical conclusions prior to taking any formal legal action."
)


def get_embedding(query: str) -> List[float]:
    """Generate a vector embedding via Ollama API."""
    if not query or not query.strip():
        raise ValueError("Cannot embed empty text.")

    payload = {
        "model": settings.OLLAMA_EMBED_MODEL,
        "input": query
    }

    try:
        with httpx.Client(timeout=settings.EMBED_TIMEOUT) as client:
            resp = client.post(f"{settings.OLLAMA_EMBED_HOST}/api/embed", json=payload)
            
            # If /api/embed fails with 404, fallback to legacy /api/embeddings endpoint
            if resp.status_code == 404:
                resp = client.post(
                    f"{settings.OLLAMA_EMBED_HOST}/api/embeddings",
                    json={"model": settings.OLLAMA_EMBED_MODEL, "prompt": query}
                )
                resp.raise_for_status()
                embedding = resp.json().get("embedding", [])
                if embedding:
                    return embedding
                raise ValueError("Legacy Ollama endpoint returned empty embedding.")
                
            resp.raise_for_status()
            data = resp.json()
            embeddings = data.get("embeddings", [])
            if embeddings and len(embeddings) > 0 and len(embeddings[0]) > 0:
                return embeddings[0]
            raise ValueError(f"Ollama returned unexpected payload structure: {data}")
            
    except httpx.ConnectError as e:
        logger.error(f"Failed to connect to Ollama embedding service at {settings.OLLAMA_EMBED_HOST}: {e}")
        raise ConnectionError(
            f"Could not connect to Ollama at {settings.OLLAMA_EMBED_HOST}. "
            f"Please verify Ollama is running and has the '{settings.OLLAMA_EMBED_MODEL}' model pulled."
        ) from e
    except Exception as e:
        logger.error(f"Embedding generation error: {e}")
        raise


def retrieve_laws(
    query_vector: List[float],
    limit: Optional[int] = None,
    state_filter: Optional[str] = None,
    city_filter: Optional[str] = None,
    db_session: Optional[Session] = None
) -> List[Dict]:
    """Retrieve laws matching the query embedding using cosine similarity."""
    limit = limit or settings.DEFAULT_RETRIEVAL_LIMIT
    close_session = False
    db = db_session
    if db is None:
        db = SessionLocal()
        close_session = True

    try:
        vec_str = '[' + ','.join(str(v) for v in query_vector) + ']'
        
        query_conditions = ["embedding IS NOT NULL"]
        params = {"vec": vec_str, "limit": limit}
        
        if state_filter:
            query_conditions.append("state = :state")
            params["state"] = state_filter.strip().upper()
        if city_filter:
            query_conditions.append("LOWER(city_or_county) = LOWER(:city)")
            params["city"] = city_filter.strip()
            
        # Whitelist verification for dynamic query clauses
        allowed_clauses = {
            "embedding IS NOT NULL",
            "state = :state",
            "LOWER(city_or_county) = LOWER(:city)"
        }
        for clause in query_conditions:
            if clause not in allowed_clauses:
                raise ValueError(f"Unauthorized SQL query clause: {clause}")

        conditions_str = " AND ".join(query_conditions)
        is_sqlite = db.bind.dialect.name == "sqlite"
        
        if is_sqlite:
            # Fallback for local unit test fixtures without pgvector extension:
            # Extract candidates and compute exact cosine similarity in Python for realistic ranking
            sql = text(f"""
                SELECT id, jurisdiction, state, city_or_county, title, section, content, embedding
                FROM laws_vectors
                WHERE {conditions_str}
            """)
            rows = db.execute(sql, params).fetchall()
            results = []
            norm_q = math.sqrt(sum(a * a for a in query_vector))
            for row in rows:
                sim = 0.0
                if row.embedding:
                    try:
                        emb = json.loads(row.embedding) if isinstance(row.embedding, str) else row.embedding
                        dot = sum(a * b for a, b in zip(query_vector, emb))
                        norm_e = math.sqrt(sum(b * b for b in emb))
                        if norm_q > 0 and norm_e > 0:
                            sim = dot / (norm_q * norm_e)
                    except Exception:
                        sim = 0.0
                results.append({
                    "id": row.id,
                    "jurisdiction": row.jurisdiction,
                    "state": row.state,
                    "city_or_county": row.city_or_county,
                    "title": row.title,
                    "section": row.section,
                    "content": row.content,
                    "similarity": float(sim)
                })
            results.sort(key=lambda x: x["similarity"], reverse=True)
            return results[:limit]
        else:
            # Production pgvector cosine distance: 1 - (embedding <=> vec)
            sql = text(f"""
                SELECT id, jurisdiction, state, city_or_county, title, section, content,
                       (1 - (embedding <=> CAST(:vec AS vector))) AS cosine_sim
                FROM laws_vectors
                WHERE {conditions_str}
                ORDER BY embedding <=> CAST(:vec AS vector)
                LIMIT :limit
            """)
            rows = db.execute(sql, params).fetchall()
            results = []
            for row in rows:
                results.append({
                    "id": row.id,
                    "jurisdiction": row.jurisdiction,
                    "state": row.state,
                    "city_or_county": row.city_or_county,
                    "title": row.title,
                    "section": row.section,
                    "content": row.content,
                    "similarity": float(row.cosine_sim) if row.cosine_sim is not None else 0.0
                })
            return results
    except Exception as e:
        logger.error(f"Vector search retrieval error: {e}")
        return []
    finally:
        if close_session:
            db.close()


def extract_section_identifiers(text_content: str) -> Set[str]:
    """Extract normalized section numbers and statutory identifiers from legal text."""
    if not text_content:
        return set()
    patterns = [
        r'(?:§+|Section|Sec\.)\s*([0-9]+[A-Za-z0-9\.\-]*)',
        r'\b(?:CC|Civ\.\s*Code|Gov\.\s*Code|Health\s*&\s*Saf\.\s*Code|Admin\.\s*Code)\s*§*\s*([0-9]+[A-Za-z0-9\.\-]*)',
    ]
    sections = set()
    for pattern in patterns:
        matches = re.finditer(pattern, text_content, re.IGNORECASE)
        for m in matches:
            sec = m.group(1).strip().rstrip('.,;:')
            if sec:
                sections.add(sec)
    return sections


def is_section_grounded(cited_sec: str, authorized_sections: Set[str]) -> bool:
    """Check if a cited section matches or derives from an authorized section."""
    cited_norm = re.sub(r'[\(\)\[\]]', '', cited_sec).lower()
    for auth in authorized_sections:
        auth_norm = re.sub(r'[\(\)\[\]]', '', auth).lower()
        if cited_norm == auth_norm or cited_norm.startswith(auth_norm) or auth_norm.startswith(cited_norm):
            return True
    return False


def verify_citation_grounding(analysis_text: str, laws: List[Dict]) -> Tuple[bool, List[str], str]:
    """
    Verify whether statutory citations in the generated brief are grounded in retrieved laws.
    Returns:
        (is_grounded, ungrounded_citations, advisory_markdown)
    """
    if not laws:
        return False, [], ""

    # Aggregate authorized section numbers from retrieved record
    authorized_sections: Set[str] = set()
    for law in laws:
        authorized_sections.update(extract_section_identifiers(law.get("section", "")))
        authorized_sections.update(extract_section_identifiers(law.get("title", "")))

    # Extract cited section numbers in the generated brief
    raw_citations = extract_section_identifiers(analysis_text)
    # Disregard single-digit heading numbers ("1", "2", "3", "4") that match outline formatting
    valid_citations = {s for s in raw_citations if len(s) > 1 or (s.isdigit() and int(s) > 10)}

    ungrounded = []
    for citation in sorted(valid_citations):
        if not is_section_grounded(citation, authorized_sections):
            ungrounded.append(citation)

    if ungrounded:
        formatted_list = "\n".join(f"> - `Section {c}`" for c in ungrounded)
        notice = (
            "\n\n---\n\n"
            "> ⚠️ **Citation Grounding Advisory (Potential Hallucination Risk)**:\n"
            "> The following statutory sections cited in this brief were **not present in the retrieved authority record** "
            "and may reflect model fabrication or ungrounded training priors:\n"
            f"{formatted_list}\n"
            ">\n"
            "> KruschLaw mandates that counsel independently verify whether these provisions are enacted, controlling, "
            "and unrepealed before relying upon them in legal pleadings or advisory opinions."
        )
        return False, ungrounded, notice
    else:
        notice = (
            "\n\n---\n\n"
            "> 🛡️ **Citation Grounding Verified**: All statutory citations in this brief correspond directly to retrieved authorities."
        )
        return True, [], notice


def generate_legal_analysis(case_facts: str, case_title: str, laws: List[Dict]) -> str:
    """Generate structured legal analysis grounding client matter facts with retrieved laws."""
    if not laws:
        return (
            "### ⚠️ No Relevant Authorities Found\n\n"
            "No relevant statutes or ordinances were found in the database matching the matter facts. "
            "Please ensure you have ingested applicable municipal or state datasets.\n\n"
            f"> **Note**: {UPL_DISCLAIMER}"
        )

    # Format retrieved legal citations
    context_blocks = []
    for idx, law in enumerate(laws, 1):
        loc = []
        if law.get("state"):
            loc.append(f"State: {law['state']}")
        if law.get("city_or_county"):
            loc.append(f"Jurisdiction: {law['city_or_county']}")
        loc_str = ", ".join(loc) if loc else "Federal / General"
        
        sim_pct = round(law.get("similarity", 0.0) * 100, 1)
        block = (
            f"[{idx}] {law.get('title', 'Unknown Title')} — {law.get('section', 'General')}\n"
            f"Authority: {law.get('jurisdiction', 'Municipal Code')} ({loc_str}) [Relevance Match: {sim_pct}%]\n"
            f"Text:\n{law.get('content', '').strip()}\n"
        )
        context_blocks.append(block)

    context_str = "\n---\n".join(context_blocks)

    system_prompt = (
        "You are KruschLaw, an air-gapped, privacy-first legal research engine designed for law firms. "
        "Your task is to produce a rigorous, citation-grounded preliminary case analysis based ONLY on the provided "
        "statutes, municipal ordinances, and factual statement.\n\n"
        "CRITICAL INSTRUCTIONS:\n"
        "- Ground all legal assertions strictly in the provided authority record.\n"
        "- Do NOT cite or invent statutory sections that do not appear in the retrieved context.\n"
        "- If an issue is not governed by the retrieved laws, explicitly state that no local authority was retrieved.\n\n"
        "Analyze the case using the following mandatory headings:\n"
        "1. **Executive Summary**: Core legal conclusion in 2-3 sentences.\n"
        "2. **Applicable Legal Authority & Statutory Citations**: Cite each relevant section by name and number.\n"
        "3. **Factual Matrix Analysis**: Connect specific facts from the matter to the statutory elements.\n"
        "4. **Potential Defenses, Liabilities & Next Steps**: Concrete strategic considerations for counsel."
    )

    user_prompt = f"""=== MATTER TITLE ===
{case_title}

=== MATTER FACTUAL RECORD ===
{case_facts}

=== RETRIEVED RELEVANT STATUTES & ORDINANCES ===
{context_str}

=== INSTRUCTIONS ===
Draft the legal analysis following the required headings. Conclude with an ethical reminder for counsel."""

    try:
        with httpx.Client(timeout=settings.LLM_TIMEOUT) as client:
            resp = client.post(
                f"{settings.OLLAMA_BASE_URL}/api/generate",
                json={
                    "model": settings.OLLAMA_LLM_MODEL,
                    "system": system_prompt,
                    "prompt": user_prompt,
                    "stream": False,
                    "options": {
                        "temperature": 0.2,
                        "num_ctx": 8192
                    }
                }
            )
            resp.raise_for_status()
            analysis_text = resp.json().get("response", "").strip()
            
            # Grounding verification guardrail
            _, _, grounding_notice = verify_citation_grounding(analysis_text, laws)

            # Append grounding notice and formal UPL disclaimer
            full_response = f"{analysis_text}{grounding_notice}\n\n---\n\n> ⚖️ **Ethical & Regulatory Notice**:\n> {UPL_DISCLAIMER}"
            return full_response
            
    except httpx.ConnectError as e:
        return (
            f"### ❌ Inference Connection Error\n\n"
            f"Could not connect to the local LLM at `{settings.OLLAMA_BASE_URL}`. "
            f"Please verify that Ollama is active and that the model `{settings.OLLAMA_LLM_MODEL}` is loaded.\n\n"
            f"**Error Details**: {e}"
        )
    except Exception as e:
        return f"### ❌ Error Generating Analysis\n\nAn unexpected error occurred during analysis generation: {str(e)}"

