import re
import json
import math
import logging
import httpx
from typing import List, Dict, Optional, Tuple, Set
from sqlalchemy import text
from sqlalchemy.orm import Session

from .config import settings
from .db import SessionLocal

logger = logging.getLogger("kruschlaw.rag")

UPL_DISCLAIMER = (
    "DISCLAIMER: This analysis was generated by KruschLaw, an offline, air-gapped AI research engine. "
    "This material is provided strictly for exploratory legal research and preliminary issue-spotting. "
    "It does NOT constitute legal advice, formal representation, or an attorney-client relationship. "
    "A licensed attorney admitted to practice in the relevant jurisdiction must independently verify "
    "all cited statutes, local ordinances, and analytical conclusions prior to taking any formal legal action."
)


class RetrievalError(RuntimeError):
    """Raised when statutory or ordinance search against the database fails."""
    pass


def get_embeddings_batch(queries: List[str]) -> List[List[float]]:
    """Generate vector embeddings in batch via Ollama API."""
    if not queries:
        return []
    clean_queries = [q.strip() if q and q.strip() else " " for q in queries]
    payload = {
        "model": settings.OLLAMA_EMBED_MODEL,
        "input": clean_queries
    }
    try:
        timeout = max(settings.EMBED_TIMEOUT, settings.EMBED_TIMEOUT * (len(clean_queries) / 8.0))
        with httpx.Client(timeout=timeout) as client:
            resp = client.post(f"{settings.OLLAMA_EMBED_HOST}/api/embed", json=payload)
            if resp.status_code == 200:
                data = resp.json()
                embeddings = data.get("embeddings", [])
                if len(embeddings) == len(clean_queries):
                    return embeddings
            # Fallback to sequential calls
            return [get_embedding(q) for q in clean_queries]
    except Exception as e:
        logger.warning(f"Batch embedding request failed ({e}), falling back to sequential embedding.")
        return [get_embedding(q) for q in clean_queries]


def get_embedding(query: str) -> List[float]:
    """Generate a vector embedding via Ollama API."""
    if not query or not query.strip():
        raise ValueError("Cannot embed empty text.")

    payload = {
        "model": settings.OLLAMA_EMBED_MODEL,
        "input": query
    }

    try:
        with httpx.Client(timeout=settings.EMBED_TIMEOUT) as client:
            resp = client.post(f"{settings.OLLAMA_EMBED_HOST}/api/embed", json=payload)
            
            # If /api/embed fails with 404, fallback to legacy /api/embeddings endpoint
            if resp.status_code == 404:
                resp = client.post(
                    f"{settings.OLLAMA_EMBED_HOST}/api/embeddings",
                    json={"model": settings.OLLAMA_EMBED_MODEL, "prompt": query}
                )
                resp.raise_for_status()
                embedding = resp.json().get("embedding", [])
                if embedding:
                    return embedding
                raise ValueError("Legacy Ollama endpoint returned empty embedding.")
                
            resp.raise_for_status()
            data = resp.json()
            embeddings = data.get("embeddings", [])
            if embeddings and len(embeddings) > 0 and len(embeddings[0]) > 0:
                return embeddings[0]
            raise ValueError(f"Ollama returned unexpected payload structure: {data}")
            
    except httpx.ConnectError as e:
        logger.error(f"Failed to connect to Ollama embedding service at {settings.OLLAMA_EMBED_HOST}: {e}")
        raise ConnectionError(
            f"Could not connect to Ollama at {settings.OLLAMA_EMBED_HOST}. "
            f"Please verify Ollama is running and has the '{settings.OLLAMA_EMBED_MODEL}' model pulled."
        ) from e
    except Exception as e:
        logger.error(f"Embedding generation error: {e}")
        raise


def retrieve_laws(
    query_vector: Optional[List[float]] = None,
    text_query: Optional[str] = None,
    limit: Optional[int] = None,
    state_filter: Optional[str] = None,
    city_filter: Optional[str] = None,
    topic_filter: Optional[str] = None,
    db_session: Optional[Session] = None
) -> List[Dict]:
    """
    Retrieve laws using hybrid search: combining pgvector cosine similarity
    with full-text lexical ranking (tsvector on PostgreSQL, token match on SQLite),
    followed by parent-section deduplication.
    """
    limit = limit or settings.DEFAULT_RETRIEVAL_LIMIT
    close_session = False
    db = db_session
    if db is None:
        db = SessionLocal()
        close_session = True

    try:
        # If query vector is missing but text_query exists, compute vector
        if query_vector is None and text_query:
            query_vector = get_embedding(text_query)

        query_conditions = ["is_substantive = 1" if db.bind.dialect.name == "sqlite" else "is_substantive = true"]
        params: Dict = {"limit": limit * 2}  # Retrieve extra for chunk deduplication

        if state_filter:
            query_conditions.append("state = :state")
            params["state"] = state_filter.strip().upper()
        if city_filter:
            query_conditions.append("(LOWER(city_or_county) = LOWER(:city) OR LOWER(city) = LOWER(:city))")
            params["city"] = city_filter.strip()
        if topic_filter:
            query_conditions.append("LOWER(topic) = LOWER(:topic)")
            params["topic"] = topic_filter.strip()

        conditions_str = " AND ".join(query_conditions)
        is_sqlite = db.bind.dialect.name == "sqlite"

        if is_sqlite:
            # SQLite fallback: hybrid cosine similarity + lexical keyword scoring
            sql = text(f"""
                SELECT id, jurisdiction, state, city, county, city_or_county, topic, title, section, content, chunk_index, embedding
                FROM laws_vectors
                WHERE {conditions_str}
            """)
            rows = db.execute(sql, params).fetchall()
            results = []
            norm_q = math.sqrt(sum(a * a for a in query_vector)) if query_vector else 0.0

            # Tokenize query for lexical scoring
            query_tokens = set(re.findall(r'\b[a-zA-Z0-9\.\-]{3,}\b', text_query.lower())) if text_query else set()

            for row in rows:
                cos_sim = 0.0
                if query_vector and row.embedding:
                    try:
                        emb = json.loads(row.embedding) if isinstance(row.embedding, str) else row.embedding
                        dot = sum(a * b for a, b in zip(query_vector, emb))
                        norm_e = math.sqrt(sum(b * b for b in emb))
                        if norm_q > 0 and norm_e > 0:
                            cos_sim = dot / (norm_q * norm_e)
                    except Exception:
                        cos_sim = 0.0

                lex_score = 0.0
                if query_tokens:
                    doc_text = f"{row.title or ''} {row.section or ''} {row.content or ''}".lower()
                    matches = sum(1 for t in query_tokens if t in doc_text)
                    lex_score = min(1.0, matches / max(1, len(query_tokens)))

                # Weighted hybrid score: 70% vector semantic, 30% lexical keyword
                combined_sim = (0.7 * cos_sim) + (0.3 * lex_score) if text_query and query_vector else (cos_sim or lex_score)

                results.append({
                    "id": row.id,
                    "jurisdiction": row.jurisdiction,
                    "state": row.state,
                    "city": row.city or row.city_or_county,
                    "county": row.county,
                    "city_or_county": row.city_or_county or row.city,
                    "topic": row.topic,
                    "title": row.title,
                    "section": row.section,
                    "content": row.content,
                    "chunk_index": row.chunk_index,
                    "similarity": float(combined_sim)
                })

            results.sort(key=lambda x: x["similarity"], reverse=True)
        else:
            # Production PostgreSQL: Hybrid tsvector + pgvector query
            vec_str = '[' + ','.join(str(v) for v in query_vector) + ']' if query_vector else None
            params["vec"] = vec_str
            clean_text_q = re.sub(r'[^a-zA-Z0-9\s]', ' ', text_query or "").strip()
            params["text_q"] = clean_text_q if clean_text_q else ""

            if clean_text_q and vec_str:
                sql = text(f"""
                    WITH vec_matches AS (
                        SELECT id, (1 - (embedding <=> CAST(:vec AS vector))) AS cos_sim,
                               ROW_NUMBER() OVER (ORDER BY embedding <=> CAST(:vec AS vector)) as v_rank
                        FROM laws_vectors
                        WHERE {conditions_str} AND embedding IS NOT NULL
                        LIMIT 50
                    ),
                    lex_matches AS (
                        SELECT id, ts_rank_cd(to_tsvector('english', coalesce(title, '') || ' ' || coalesce(section, '') || ' ' || coalesce(content, '')), plainto_tsquery('english', :text_q)) as l_score,
                               ROW_NUMBER() OVER (ORDER BY ts_rank_cd(to_tsvector('english', coalesce(title, '') || ' ' || coalesce(section, '') || ' ' || coalesce(content, '')), plainto_tsquery('english', :text_q)) DESC) as l_rank
                        FROM laws_vectors
                        WHERE {conditions_str} AND to_tsvector('english', coalesce(title, '') || ' ' || coalesce(section, '') || ' ' || coalesce(content, '')) @@ plainto_tsquery('english', :text_q)
                        LIMIT 50
                    )
                    SELECT l.id, l.jurisdiction, l.state, l.city, l.county, l.city_or_county, l.topic, l.title, l.section, l.content, l.chunk_index,
                           COALESCE(1.0 / (60 + v.v_rank), 0.0) + COALESCE(1.0 / (60 + lex.l_rank), 0.0) AS hybrid_score,
                           COALESCE(v.cos_sim, 0.0) as similarity
                    FROM laws_vectors l
                    LEFT JOIN vec_matches v ON l.id = v.id
                    LEFT JOIN lex_matches lex ON l.id = lex.id
                    WHERE v.id IS NOT NULL OR lex.id IS NOT NULL
                    ORDER BY hybrid_score DESC
                    LIMIT :limit
                """)
            elif vec_str:
                sql = text(f"""
                    SELECT id, jurisdiction, state, city, county, city_or_county, topic, title, section, content, chunk_index,
                           (1 - (embedding <=> CAST(:vec AS vector))) AS similarity
                    FROM laws_vectors
                    WHERE {conditions_str} AND embedding IS NOT NULL
                    ORDER BY embedding <=> CAST(:vec AS vector)
                    LIMIT :limit
                """)
            else:
                sql = text(f"""
                    SELECT id, jurisdiction, state, city, county, city_or_county, topic, title, section, content, chunk_index,
                           ts_rank_cd(to_tsvector('english', coalesce(title, '') || ' ' || coalesce(section, '') || ' ' || coalesce(content, '')), plainto_tsquery('english', :text_q)) AS similarity
                    FROM laws_vectors
                    WHERE {conditions_str} AND to_tsvector('english', coalesce(title, '') || ' ' || coalesce(section, '') || ' ' || coalesce(content, '')) @@ plainto_tsquery('english', :text_q)
                    ORDER BY similarity DESC
                    LIMIT :limit
                """)

            rows = db.execute(sql, params).fetchall()
            results = []
            for row in rows:
                results.append({
                    "id": row.id,
                    "jurisdiction": row.jurisdiction,
                    "state": row.state,
                    "city": row.city or row.city_or_county,
                    "county": row.county,
                    "city_or_county": row.city_or_county or row.city,
                    "topic": row.topic,
                    "title": row.title,
                    "section": row.section,
                    "content": row.content,
                    "chunk_index": getattr(row, "chunk_index", 0),
                    "similarity": float(row.similarity) if getattr(row, "similarity", None) is not None else 0.0
                })

        # Parent-Child deduplication: avoid multiple chunks of identical section crowding out top-k
        seen_sections: Set[Tuple[str, str, str]] = set()
        deduped: List[Dict] = []
        for r in results:
            sec_key = (r["jurisdiction"], r.get("state") or "", r.get("section") or r.get("title") or str(r["id"]))
            if sec_key not in seen_sections:
                seen_sections.add(sec_key)
                deduped.append(r)
            if len(deduped) >= limit:
                break

        return deduped
    except Exception as e:
        logger.error(f"Vector search retrieval error: {e}", exc_info=True)
        raise RetrievalError(f"Database statutory retrieval failed: {str(e)}") from e
    finally:
        if close_session:
            db.close()


def extract_section_identifiers(text_content: str) -> Set[str]:
    """Extract normalized section numbers and statutory identifiers from legal text."""
    if not text_content:
        return set()
    patterns = [
        r'(?:§+|Section|Sec\.)\s*([0-9]+[A-Za-z0-9\.\-]*)',
        r'\b(?:CC|Civ\.\s*Code|Gov\.\s*Code|Health\s*&\s*Saf\.\s*Code|Admin\.\s*Code)\s*§*\s*([0-9]+[A-Za-z0-9\.\-]*)',
    ]
    sections = set()
    for pattern in patterns:
        matches = re.finditer(pattern, text_content, re.IGNORECASE)
        for m in matches:
            sec = m.group(1).strip().rstrip('.,;:')
            if sec:
                sections.add(sec)
    return sections


def is_section_grounded(cited_sec: str, authorized_sections: Set[str]) -> bool:
    """Check if a cited section matches or derives from an authorized section."""
    cited_norm = re.sub(r'[\(\)\[\]]', '', cited_sec).lower()
    for auth in authorized_sections:
        auth_norm = re.sub(r'[\(\)\[\]]', '', auth).lower()
        if cited_norm == auth_norm or cited_norm.startswith(auth_norm) or auth_norm.startswith(cited_norm):
            return True
    return False


def verify_citation_grounding(analysis_text: str, laws: List[Dict]) -> Tuple[bool, List[str], str]:
    """
    Verify whether statutory citations and quote spans in the generated brief
    are grounded in retrieved laws.
    Returns:
        (is_grounded, ungrounded_items, advisory_markdown)
    """
    if not laws:
        return False, [], ""

    # Aggregate authorized section numbers and full text corpus
    authorized_sections: Set[str] = set()
    corpus_text = ""
    for law in laws:
        authorized_sections.update(extract_section_identifiers(law.get("section", "")))
        authorized_sections.update(extract_section_identifiers(law.get("title", "")))
        corpus_text += " " + (law.get("content") or "")

    corpus_lower = corpus_text.lower()

    # 1. Extract cited section numbers in the generated brief
    raw_citations = extract_section_identifiers(analysis_text)
    # Disregard single-digit heading numbers ("1", "2", "3", "4") that match outline formatting
    valid_citations = {s for s in raw_citations if len(s) > 1 or (s.isdigit() and int(s) > 10)}

    ungrounded_cites = []
    for citation in sorted(valid_citations):
        if not is_section_grounded(citation, authorized_sections):
            ungrounded_cites.append(citation)

    # 2. Extract quotes (20+ chars) from analysis to verify quote-span overlap
    quotes = re.findall(r'["“]([^"”]{20,})["”]', analysis_text)
    ungrounded_quotes = []
    for q in quotes:
        clean_q = re.sub(r'\s+', ' ', q).strip().lower()
        # Check if the quote or a substantial portion appears in the authority corpus
        if clean_q not in corpus_lower and len(clean_q) > 25:
            # Check 70% word overlap
            q_words = set(clean_q.split())
            if q_words and sum(1 for w in q_words if w in corpus_lower) / len(q_words) < 0.6:
                ungrounded_quotes.append(q[:60] + ("..." if len(q) > 60 else ""))

    issues = []
    if ungrounded_cites:
        formatted_cites = "\n".join(f"> - `Section {c}`" for c in ungrounded_cites)
        issues.append(f"> **Ungrounded Statutory Sections** (not found in retrieved authorities):\n{formatted_cites}")
    if ungrounded_quotes:
        formatted_quotes = "\n".join(f"> - *\"{q}\"*" for q in ungrounded_quotes)
        issues.append(f"> **Unverified Verbatim Quotes** (quote text not found in retrieved authorities):\n{formatted_quotes}")

    if issues:
        notice = (
            "\n\n---\n\n"
            "> ⚠️ **Citation & Grounding Advisory (Potential Hallucination Risk)**:\n"
            "> The following citations or quotes in this brief were **not verified against retrieved authorities**:\n"
            + "\n>\n".join(issues) +
            "\n>\n"
            "> KruschLaw mandates that counsel independently verify whether these provisions and excerpts are authentic, "
            "controlling, and unrepealed prior to relying upon them."
        )
        return False, ungrounded_cites + ungrounded_quotes, notice
    else:
        notice = (
            "\n\n---\n\n"
            "> 🛡️ **Citation Grounding Verified**: All statutory citations and textual quotes correspond directly to retrieved authorities."
        )
        return True, [], notice


def generate_legal_analysis(case_facts: str, case_title: str, laws: List[Dict]) -> str:
    """Generate structured legal analysis grounding client matter facts with retrieved laws."""
    if not laws:
        return (
            "### ⚠️ No Relevant Authorities Found\n\n"
            "No relevant statutes or ordinances were found in the database matching the matter facts. "
            "Please ensure you have ingested applicable municipal or state datasets.\n\n"
            f"> **Note**: {UPL_DISCLAIMER}"
        )

    # Format retrieved legal citations
    context_blocks = []
    for idx, law in enumerate(laws, 1):
        loc = []
        if law.get("state"):
            loc.append(f"State: {law['state']}")
        if law.get("city_or_county"):
            loc.append(f"Jurisdiction: {law['city_or_county']}")
        loc_str = ", ".join(loc) if loc else "Federal / General"
        
        sim_pct = round(law.get("similarity", 0.0) * 100, 1)
        block = (
            f"[{idx}] {law.get('title', 'Unknown Title')} — {law.get('section', 'General')}\n"
            f"Authority: {law.get('jurisdiction', 'Municipal Code')} ({loc_str}) [Relevance Match: {sim_pct}%]\n"
            f"Text:\n{law.get('content', '').strip()}\n"
        )
        context_blocks.append(block)

    context_str = "\n---\n".join(context_blocks)

    system_prompt = (
        "You are KruschLaw, an air-gapped, privacy-first legal research engine designed for law firms. "
        "Your task is to produce a rigorous, citation-grounded preliminary case analysis based ONLY on the provided "
        "statutes, municipal ordinances, and factual statement.\n\n"
        "CRITICAL INSTRUCTIONS:\n"
        "- Ground all legal assertions strictly in the provided authority record.\n"
        "- Do NOT cite or invent statutory sections that do not appear in the retrieved context.\n"
        "- If an issue is not governed by the retrieved laws, explicitly state that no local authority was retrieved.\n\n"
        "Analyze the case using the following mandatory headings:\n"
        "1. **Executive Summary**: Core legal conclusion in 2-3 sentences.\n"
        "2. **Applicable Legal Authority & Statutory Citations**: Cite each relevant section by name and number.\n"
        "3. **Factual Matrix Analysis**: Connect specific facts from the matter to the statutory elements.\n"
        "4. **Potential Defenses, Liabilities & Next Steps**: Concrete strategic considerations for counsel."
    )

    user_prompt = f"""=== MATTER TITLE ===
{case_title}

=== MATTER FACTUAL RECORD ===
{case_facts}

=== RETRIEVED RELEVANT STATUTES & ORDINANCES ===
{context_str}

=== INSTRUCTIONS ===
Draft the legal analysis following the required headings. Conclude with an ethical reminder for counsel."""

    try:
        with httpx.Client(timeout=settings.LLM_TIMEOUT) as client:
            resp = client.post(
                f"{settings.OLLAMA_BASE_URL}/api/generate",
                json={
                    "model": settings.OLLAMA_LLM_MODEL,
                    "system": system_prompt,
                    "prompt": user_prompt,
                    "stream": False,
                    "options": {
                        "temperature": 0.2,
                        "num_ctx": 8192
                    }
                }
            )
            resp.raise_for_status()
            analysis_text = resp.json().get("response", "").strip()
            
            # Grounding verification guardrail
            _, _, grounding_notice = verify_citation_grounding(analysis_text, laws)

            # Append grounding notice and formal UPL disclaimer
            full_response = f"{analysis_text}{grounding_notice}\n\n---\n\n> ⚖️ **Ethical & Regulatory Notice**:\n> {UPL_DISCLAIMER}"
            return full_response
            
    except httpx.ConnectError as e:
        return (
            f"### ❌ Inference Connection Error\n\n"
            f"Could not connect to the local LLM at `{settings.OLLAMA_BASE_URL}`. "
            f"Please verify that Ollama is active and that the model `{settings.OLLAMA_LLM_MODEL}` is loaded.\n\n"
            f"**Error Details**: {e}"
        )
    except Exception as e:
        return f"### ❌ Error Generating Analysis\n\nAn unexpected error occurred during analysis generation: {str(e)}"

