"""initial_legal_graph_schema

Revision ID: c94426674038
Revises:
Create Date: 2026-09-22 22:29:09.482142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.backend.db


# revision identifiers, used by Alembic.
revision: str = 'c94426674038'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('actor_key_hash', sa.String(length=64), nullable=True),
    sa.Column('client_ip', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=True),
    sa.Column('retrieved_section_ids', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('grounding_verdict', sa.String(length=50), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_key_hash'), 'audit_logs', ['actor_key_hash'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_matter_id'), 'audit_logs', ['matter_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_number', sa.String(length=50), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('facts', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('embedding', src.backend.db.Vector(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_index(op.f('ix_cases_is_deleted'), 'cases', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_cases_matter_number'), 'cases', ['matter_number'], unique=False)
    op.create_index(op.f('ix_cases_title'), 'cases', ['title'], unique=False)
    op.create_table('grounding_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('total_claims', sa.Integer(), nullable=False),
    sa.Column('supported_claims', sa.Integer(), nullable=False),
    sa.Column('unsupported_claims', sa.Integer(), nullable=False),
    sa.Column('invented_citations', sa.Integer(), nullable=False),
    sa.Column('stale_law_citations', sa.Integer(), nullable=False),
    sa.Column('pass_rate', sa.Float(), nullable=False),
    sa.Column('claims_json', sa.Text(), nullable=False),
    sa.Column('advisory_markdown', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grounding_reports_case_id'), 'grounding_reports', ['case_id'], unique=False)
    op.create_index(op.f('ix_grounding_reports_created_at'), 'grounding_reports', ['created_at'], unique=False)
    op.create_table('ingest_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('raw_file_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('inserted_records', sa.Integer(), nullable=False),
    sa.Column('last_committed_offset', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ocr_pages', sa.Integer(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('chunks_total', sa.Integer(), nullable=False),
    sa.Column('chunks_embedded', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_jobs_raw_file_hash'), 'ingest_jobs', ['raw_file_hash'], unique=False)
    op.create_index(op.f('ix_ingest_jobs_status'), 'ingest_jobs', ['status'], unique=False)
    op.create_table('laws_vectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('city_or_county', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_header', sa.Text(), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('is_substantive', sa.Boolean(), nullable=False),
    sa.Column('embedding', src.backend.db.Vector(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('parent_section', sa.String(length=100), nullable=True),
    sa.Column('hierarchy_level', sa.String(length=50), nullable=False),
    sa.Column('definitions_ref', sa.String(length=100), nullable=True),
    sa.Column('exceptions_ref', sa.String(length=100), nullable=True),
    sa.Column('authority_class', sa.String(length=50), nullable=False),
    sa.Column('jurisdiction_level', sa.String(length=50), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amended_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repealed', sa.Boolean(), nullable=False),
    sa.Column('preempted_by', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction', 'state', 'city', 'section', 'chunk_index', name='uq_law_section_chunk')
    )
    op.create_index(op.f('ix_laws_vectors_authority_class'), 'laws_vectors', ['authority_class'], unique=False)
    op.create_index(op.f('ix_laws_vectors_city'), 'laws_vectors', ['city'], unique=False)
    op.create_index(op.f('ix_laws_vectors_city_or_county'), 'laws_vectors', ['city_or_county'], unique=False)
    op.create_index(op.f('ix_laws_vectors_county'), 'laws_vectors', ['county'], unique=False)
    op.create_index(op.f('ix_laws_vectors_hierarchy_level'), 'laws_vectors', ['hierarchy_level'], unique=False)
    op.create_index(op.f('ix_laws_vectors_id'), 'laws_vectors', ['id'], unique=False)
    op.create_index(op.f('ix_laws_vectors_jurisdiction'), 'laws_vectors', ['jurisdiction'], unique=False)
    op.create_index(op.f('ix_laws_vectors_jurisdiction_level'), 'laws_vectors', ['jurisdiction_level'], unique=False)
    op.create_index(op.f('ix_laws_vectors_parent_id'), 'laws_vectors', ['parent_id'], unique=False)
    op.create_index(op.f('ix_laws_vectors_parent_section'), 'laws_vectors', ['parent_section'], unique=False)
    op.create_index(op.f('ix_laws_vectors_repealed'), 'laws_vectors', ['repealed'], unique=False)
    op.create_index(op.f('ix_laws_vectors_section'), 'laws_vectors', ['section'], unique=False)
    op.create_index(op.f('ix_laws_vectors_source_hash'), 'laws_vectors', ['source_hash'], unique=False)
    op.create_index(op.f('ix_laws_vectors_state'), 'laws_vectors', ['state'], unique=False)
    op.create_index(op.f('ix_laws_vectors_topic'), 'laws_vectors', ['topic'], unique=False)
    op.create_table('matter_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_locator', sa.String(length=100), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', src.backend.db.Vector(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matter_evidence_id'), 'matter_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_matter_evidence_matter_id'), 'matter_evidence', ['matter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matter_evidence_matter_id'), table_name='matter_evidence')
    op.drop_index(op.f('ix_matter_evidence_id'), table_name='matter_evidence')
    op.drop_table('matter_evidence')
    op.drop_index(op.f('ix_laws_vectors_topic'), table_name='laws_vectors')
    op.drop_index(op.f('ix_laws_vectors_state'), table_name='laws_vectors')
    op.drop_index(op.f('ix_laws_vectors_source_hash'), table_name='laws_vectors')
    op.drop_index(op.f('ix_laws_vectors_section'), table_name='laws_vectors')
    op.drop_index(op.f('ix_laws_vectors_repealed'), table_name='laws_vectors')
    op.drop_index(op.f('ix_laws_vectors_parent_section'), table_name='laws_vectors')
    op.drop_index(op.f('ix_laws_vectors_parent_id'), table_name='laws_vectors')
    op.drop_index(op.f('ix_laws_vectors_jurisdiction_level'), table_name='laws_vectors')
    op.drop_index(op.f('ix_laws_vectors_jurisdiction'), table_name='laws_vectors')
    op.drop_index(op.f('ix_laws_vectors_id'), table_name='laws_vectors')
    op.drop_index(op.f('ix_laws_vectors_hierarchy_level'), table_name='laws_vectors')
    op.drop_index(op.f('ix_laws_vectors_county'), table_name='laws_vectors')
    op.drop_index(op.f('ix_laws_vectors_city_or_county'), table_name='laws_vectors')
    op.drop_index(op.f('ix_laws_vectors_city'), table_name='laws_vectors')
    op.drop_index(op.f('ix_laws_vectors_authority_class'), table_name='laws_vectors')
    op.drop_table('laws_vectors')
    op.drop_index(op.f('ix_ingest_jobs_status'), table_name='ingest_jobs')
    op.drop_index(op.f('ix_ingest_jobs_raw_file_hash'), table_name='ingest_jobs')
    op.drop_table('ingest_jobs')
    op.drop_index(op.f('ix_grounding_reports_created_at'), table_name='grounding_reports')
    op.drop_index(op.f('ix_grounding_reports_case_id'), table_name='grounding_reports')
    op.drop_table('grounding_reports')
    op.drop_index(op.f('ix_cases_title'), table_name='cases')
    op.drop_index(op.f('ix_cases_matter_number'), table_name='cases')
    op.drop_index(op.f('ix_cases_is_deleted'), table_name='cases')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_matter_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_key_hash'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
